### ISSUE TITLE
a11y Best Practices

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#106]
# User Story

Developers of Dojo 2 should have clear guidance on how to make their applications accessible and how best to ensure their applications are accessible.

# Solution

Most of the best practices will be for custom widget authors, which is guidance about how best to ensure their widgets will behave will when integrated into an application and that the DOM a widget generates is accessible.

**Comment by dylans** [comment]
We may want to consider the [`prefers-reduced-motion` media query](https://github.com/w3c/csswg-drafts/issues/442) somewhere in our approach for a11y. Browser support is in Safari 10.1, iOS 10.3, and perhaps others. https://css-tricks.com/introduction-reduced-motion-media-query/ has a decent summary.

There are also plans to add [CSS media query settings for contrast and transparency](https://github.com/w3c/csswg-drafts/issues/443).

**Comment by smhigley** [comment]
@dylans I like it! I think it would be nice to provide, with a caveat saying "we still recommend you make all your animations accessibility-friendly." Should we provide alternate styles for that and high contrast in themes based on a property that adds a class to the projector?

**Comment by rishson** [comment]
High-contrast theme would be really useful (as long as it doesn't clash with a user putting their OS in high contrast mode) - is that what you were suggesting?

**Comment by smhigley** [comment]
@rishson yeah, I did mean a separate high-contrast theme. Morning brain :). More contrast-y styles won't conflict with OS high contrast mode.

**Comment by dylans** [comment]
Also, should we publish the aria guidelines from our Google doc as part of the meta perhaps (either as a wiki or a document), or plan to have them as part of the reference guide?

**Comment by kitsonk** [comment]
Issue moved to [dojo/dojo.io #207](https://github.com/dojo/dojo.io/issues/207) via [**ZenHub**](https://www.zenhub.com/)
