### ISSUE TITLE
a11y State

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#109]

**Comment by agubler** [comment]
Do we have any more information about what this entails? If there is an enhancement here, should it be in @dojo/widgets?

**Comment by kitsonk** [comment]
Apologies.

Any widget should have defined when it uses [ARIA states](https://www.w3.org/TR/wai-aria/states_and_properties) to help make the widget more accessible and that the widget should have tests to ensure that the ARIA State matches the visual state of the widget throughout any lifecycle.

**Comment by agubler** [comment]
@kitsonk should we move this widgets?

**Comment by kitsonk** [comment]
Issue moved to [dojo/widgets #64](https://github.com/dojo/widgets/issues/64) via [**ZenHub**](https://www.zenhub.com/)
