### ISSUE TITLE
a11y Testing

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#110]

**Comment by agubler** [comment]
I think that this should certainly be a concern for @dojo/widgets, perhaps be good to have some more details too.

**Comment by kitsonk** [comment]
Apologies.

More details, we should leverage [`intern-a11y`](https://github.com/theintern/intern-a11y) to integrate a11y tests into for each widget and make them part of the test suite.  We should ensure that all widgets include tests the express expected results for:

- Screen Reader Expected Results
- Express expected rolls
- Are navigable via a keyboard with expected results
- Have appropriate focus during navigation

**Comment by agubler** [comment]
I think we should move this to `@dojo/widgets` unless you have any objections

**Comment by kitsonk** [comment]
Issue moved to [dojo/widgets #65](https://github.com/dojo/widgets/issues/65) via [**ZenHub**](https://www.zenhub.com/)
