### ISSUE TITLE
Publishing of dojo components

### ISSUE THREAD

**Issue by rishson** [dojo/widget-core#178]
`npm` implements a policy of ‘first come first served’ when it comes to registering a name.
Because we want users to be able to import only the components that their app uses, we need to make sure that each component is published as a separate package, e.g.

```
dojo-components-textBox
dojo-components-tabPanel
```

In order to ‘claim’ these names on NPM, we need to publish a file to NPM so we are there first (the file can be ‘Hello World’ - we just need to register the names). Whilst this is not usually a problem, the number of components that we will need to publish is quite large and therefore there exists a greater risk of hitting an already claimed package name.

Before we do this, we need to agree on what the package name format is. Then we can write a quick script to register all the names in a list.

The name of the package is important as it is what the user ‘thinks’ of the component as:

`import createTextBox from 'dojo-component-textBox';`

My suggestion is for the prefix to be ‘dojo-component’ with no sub divisions such as 'form’ or ‘layout’.
Please note that we will probably also publish ‘uber’ packages of the components so a user can import all of the components at once, if required:

`import { createTextBox, createTabPanel } from 'dojo-components';`

Another option is to publish the components under our `@dojo` namespace. This has the advantage of meaning that we own all possible combinations of package names under `@dojo`, e.g.

`@dojo/component-textBox, @dojo/we-really-own-everything`

The drawbacks of this approach are that currently, namespaced packages do not work with our AMD loader [confirmation required], and also, it might confuse users if we publish some packages under our namespace and other outside it, e.g.

```
import createTextBox from '@dojo/component-textBox';
import compose from 'dojo-compose/compose';
```

**Comment by matt-gadd** [comment]
The scoped npm namespace actually has nothing to do with the AMD loader (it would be just a change to the config). It would mean a change to all of our imports to reference the `@` namespace across any repo's that consume packages (or we'd have to add config to both webpack and all of our tsconfigs - which i'd rather avoid). Or we'd have to do something similar to this https://github.com/dojo/grunt-dojo2/pull/65.

**Comment by rishson** [comment]
@matt-gadd can you clarify the above? Specifically, we'd just need to change any existing widget/component imports - so just `dojo/examples` currently?

**Comment by matt-gadd** [comment]
@rishson i'm fairly sure we'd want to publish everything to `@dojo` if we we were going to go that route (it'd be weird otherwise). which would mean changing imports everywhere.

**Comment by matt-gadd** [comment]
also we'd previously envisioned that the `uber` packages would live under the `@dojo` namespace, similar to rxjs.

**Comment by rishson** [comment]
Yeah - I remember both those conclusions earlier. My preference is to bite the bullet and move everything eventually under `@dojo` so we avoid any community confusion between 'official' dojo packages and anything else that happens to have a 'dojo-' prefix. Currently, there are no packages other than official ones with this prefix, but all it would take would be one, to throw things off.

The choice seems to be:

move nothing under `@dojo` and hope we dont get package confusion
move some parts under `@dojo` - minimising shifting work, but potentially confusing imports
move all under `@dojo` - cleaner, but requires us to do most work.

**Comment by rishson** [comment]
refs #283

**Comment by rishson** [comment]
Closing in favour of tracking #283
