### ISSUE TITLE
Foundational Widgets

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#2]
This issue is to discuss what widgets should be part of the foundational widgets, potentially located in this package, or in related packages, as we begin to develop the "out of the box" widgets.

Currently we have.  Many of these were just created to be able to try to prototype and solve problems that other widgets may need and might be questionable in the final set:
- Button - Analog of `<button>`
- Container - Simply "owns" other widgets
- Dijit - A wrapper class for Dojo 1 Dijits
- LayoutContainer - Does a level of layout on contained widgets
- List - A simple list UI component
- Panel - A simple container
- ResizePanel - Provides a handle that allows one of the contained widgets to be resized
- TabbedPanel - All children owned are displayed as tabs
- TextInput - Analog of `<input type="text">`
- Widget - A generic "dumb" widget the includes all the foundational widget functionality and can render a tag and some content.

**Comment by mwistrand** [comment]
Something comparable to `dijit/popup` whose sole purpose is to manage z-indices currently in use on the screen could also be very useful (essential?).

**Comment by dylans** [comment]
A fair number of our clients like to extend dijit/Toolbar or other Menu components to create things like Ribbon bars or other UIs to contain various tabs/buttons/other commands. It would probably overlap with a fair amount of functionality from Panel/ResizePanel/TabbedPanel.

**Comment by dylans** [comment]
Dojo 2 text inputs should support masking of input based on data format/constraints and should support i18n for that as well

**Comment by dylans** [comment]
Does not belong in the core widgets repo, but a few of our big users rely heavily on the rich text editor. Either need a modern version of dijit/Editor, or need to wrap something else such as Trix which takes a vdom approach to RTE. A key feature is doing a decent job when pasting from Word.

**Comment by dylans** [comment]
Some thoughts on validation patterns and other things that are commonly found in widget systems:

* invalid
* incomplete
* masking
* constraints
* localized (e.g. validated within a user's locale)
* display of state to users

**Comment by kitsonk** [comment]
When appropriate we should turn this into an Epic and create the separate issues to track progress.

**Comment by agubler** [comment]
@dylans do we think this should be moved to [widgets](https://github.com/dojo/widgets)?

**Comment by dylans** [comment]
@agubler yes, the challenge is that ZenHub doesn't currently support moving epics from what I can tell, so I hadn't gotten around to re-creating the ticket yet. #85 should also be moved.

**Comment by dylans** [comment]
Issue moved to [dojo/widgets #23](https://github.com/dojo/widgets/issues/23) via [**ZenHub**](https://www.zenhub.com/)
