### ISSUE TITLE
Apply theme classes to outer widget node

### ISSUE THREAD

**Issue by tomdye** [dojo/widget-core#221]
When authoring a widget, the outer-node class should be set using the classes returned from the `themeManager`.
This should not overwrite any classes passed as properties when the widget is used.

If a `classes` array is set in the `nodeAttributes` function it should be merged with the classes passed during widget creation.

Example
``` typescript
// createTabPanel.ts
nodeAttributes: [
	function(this: Widget): VNodeProperties {
		return { 
			classes: { tabPanel: true }
		};
	}
]

// app.ts
v(createTabPanel, { properties: { classes: { myTabPanelClass: true } }})
```

Expected output
``` html
<tab-panel class="tabPanel myTabPanelClass"></tab-panel>
```

**Comment by agubler** [comment]
@tomdye I believe this has been resolved by adding `render` to enable authors to add classes (and any other properties) in the same way as all other widget nodes.

so an example would be

```ts
import * as css from './styles/myCss';

const myWidget = createWidgetBase.mixin({
    mixin: {
        render(this: MyWidget): DNode {
            return v('div', { classes: this.classes(css.myClass).get() });
        }
    }
});
```
