### ISSUE TITLE
Move README contents into explanation doc

### ISSUE THREAD

**Issue by rishson** [dojo/widget-core#257]
We should make the README more aligned to FOSS README docs:

What is this repo?
Why was it written?
Why should I use it?
What alternatives are out there?
How is this project structured in terms of ownership, contributions, maintenance status etc?

Consideration of [awesome readme](https://github.com/matiassingers/awesome-readme) should be done first.

The existing contents should be migrated into a `EXPLANATION.md` until the official docs are available.

**Comment by dylans** [comment]
I actually think this is the best README we have... one of the links from the awesome readme resource you linked to is about README driven development, which goes into detail saying that the README should explain the design decisions behind the repo... I feel like the existing contents help with that goal. I agree that some of the things listed in this issue are missing from the README, but I like that this README (and compose and a few others) really explain the usage in more depth and some of the design decisions...

**Comment by agubler** [comment]
I've updated the readme PR even further, #251 and think that can probably stay as a single file. It certainly should have the following questions answered tho (in addition to the existing content).

What is this repo?
Why was it written?
Why should I use it?
What alternatives are out there?

**Comment by agubler** [comment]
@rishson do we think we can close this?

**Comment by agubler** [comment]
Closing, current README is working at the moment.
