### ISSUE TITLE
Naming convention for Mixins

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#267]
The naming convention(s) used for mixins is currently inconsistent, I am proposing that we drop the `create` prefix and leave the `Mixin` suffix.

Examples:

- `externalStateMixin`
- `themableMixin`
- `registryMixin`

**Comment by Tomdye** [comment]
Agreed.

**Comment by agubler** [comment]
@Tomdye I am proposing we would change both of those to have the `Mixin` suffix.

**Comment by Tomdye** [comment]
Ah, ok, I read it wrong. I would argue the opposite. There are contained within a folder named `mixins` thus I don't feel the need to suffix them with `Mixin`.

**Comment by agubler** [comment]
Whilst this is true and I too was a believer in the past, having worked with mixins such as `externalState` it gets very confusing because you are also dealing with properties of the same name.

I also like it because after the import line it is still obvious what it is (as you do not see the full import path everywhere something like `externalState` is referenced). If I was trying to understand code and saw `externalState` or `themeable` I would have no idea that they could be mixins.

**Comment by Tomdye** [comment]
For sure. Though there's nothing stopping you doing:
``` typescript
import themeableMixin from '../mixins/themeable';
```

**Comment by agubler** [comment]
agreed that is possible but also inconsistent (which bugs me), most people do indeed just use the class name to get the default.

**Comment by rishson** [comment]
My preference is to more closely mirror what Java did - hear me out:

Mixing are just the thing being added as a trait (usually a verb or noun if not verb-able, with a 'has' verb/noun last resort, e.g.

themeable
externalState
hasRegistry

So when you read across the definitions, it scans:

myWidget (is) themeable, (have) externalState, hasRegistry. 

Some of the benefits:
Typing 'mixin' for a mixin is tiresome and redundant 
verb-ing confers the idea that abilities are being added to a widget

I would however, suffix factories with 'factory' or prefix with 'create', to differentiate factories and mixins.

**Comment by agubler** [comment]
I think it is simpler to have a consistent suffix and still provides an indication of what the "thing" is.

I would certainly argue typing mixin with all the intellisense now days is not tiresome in the slightest, unless of course you're developing in notepad?

**Comment by rishson** [comment]
nah - still stuck in vim. Launched it a year ago and can't work out how to exit.

The mixin suffix is redundant unless we have a policy of `suffix tells you what a thing is`.
If we have suffixes then we need to be consistent and rename all `createX` to `xFactory` so that the suffix tells you what the thing is. This seems like a larger change than dropping the `mixin` suffix and keeping the `create` prefix on factories.

`myWidget (has) themeableMixin, (has) externalStateMixin`
vs
`myWidget (is) themeable, (has) externalState`

but also
`createMyWidget.mixin(createProjector)`
vs
`myWidgetFactory.mixin(projectorMixin)`

**Comment by agubler** [comment]
I don't think we need to move to `Factory` if we choose the `Mixin` suffix, we can keep the `create` prefix for classes and have a `Mixin` suffix for mixins personally. I think that is the *easiest* convention to start with personally.

The **most** important thing right now it to be consistent.

**Comment by rishson** [comment]
I agree on consistency being the most important thing. To me, a naming convention of "each thing has a type suffix, e.g. `factory`, `mixin`" is simpler than "if its a factory, it has a `create` prefix. Whereas if its a mixin, it has the `mixin` suffix".

The `create` prefix has always struck me as incongruous. It harks back to the DOM and 'createElement', which may be familiar to some of our users, but to me at least, seems like an odd convention in a reactive framework that tries to put some clear water between 'what your write' and 'the DOM'.

My eyes bleed with the tautology of `createMyWidget.mixin(themeableMixin)`.

But I could stand accused of being a grumpy old java dev, with my preference for `myWidgetFactory.mixin(themeable)`

Where's the shrug emoji when you need it.

**Comment by agubler** [comment]
Here it is just for you ¯\_(ツ)_/¯.

As you said the name `externalState` could be bad for a mixin, however for the meantime I'll raise something with to normalise them then we can continue the discussions afterwards.

**Comment by dylans** [comment]
@kitsonk's reason for create* was because anyone who has used JS has used factory methods, and they all start with create... createElement, createTextNode, etc.

**Comment by rishson** [comment]
Votes - then we can resolve pls.

```
const createMyWidget: MyWidgetFactory = createWidgetBase
	.mixin(themeable)
	.mixin(createI18nMixin)
        .mixin(...)
```
hurts my eyes..

**Comment by dylans** [comment]
Historically there's always been some sort of modifier when you create something new... whether it be:

```
var node = document.createElement();
var obj = new Foo();
```

Basically something to indicate that you are creating a new copy of something.

The challenge with the Mixin suffix is that it is redundant. Typically in Dojo 1 it was used when something could only be used as a mixin, and did not stand on its own. So I guess I would be inclined to avoid the Mixin suffix if it is included via a function with the name mixin. Does that change though with the possible switch to TS 2.2 classes? Or do we still implement our own mixin and/or functional composition utility?

**Comment by agubler** [comment]
> So I guess I would be inclined to avoid the Mixin suffix if it is included via a function with the name mixin.

I'm not sure I understand what you mean here?

**Comment by agubler** [comment]
I don't mind the `create` prefix if it is something that can instantiated/created (the new compose API will help here as we can create mixins that **cannot**) be instantiated.

For me the mixin suffix helps only mentally when consumers are importing the default export (typically the mixin itself) as they tend to name it the same thing as the module (habitual).

With out the suffix it can get confusing (i have found)

**Comment by dylans** [comment]
> So I guess I would be inclined to avoid the Mixin suffix if it is included via a function with the name mixin.
> 
> I'm not sure I understand what you mean here?

Meaning if you always include the Mixin via the .mixin() function, then you're having to type mixin twice, once for the function and once for the name of the thing being mixed in.

**Comment by dylans** [comment]
> I don't mind the create prefix if it is something that can instantiated/created (the new compose API will help here as we can create mixins that cannot) be instantiated.
> 
> For me the mixin suffix helps only mentally when consumers are importing the default export (typically the mixin itself) as they tend to name it the same thing as the module (habitual).
> 
> With out the suffix it can get confusing (i have found)

so would it be helpful to think of things that are bases/factories use create, and things that are mixins do not, or are you saying it's still confusing to keep straight that something is a mixin after it's been imported (and does it matter)?

In general, create* and *Mixin are one step towards Hungarian notation which is something we tend to avoid for everything else. I guess was is more odd as well is create as a prefix but mixin as a suffix, since it could be argued that both describe the action of how you're using them. Though over time Mixin has become a noun... and of course then there is Factory as well, though I think we got rid of that convention. Also, aren't many of the mixins already in a mixin folder?

Anyway, there's no perfect answer, but there is a reason for wanting conventions like this rather than dropping all modifiers that convey intent for usage.

**Comment by agubler** [comment]
Agree no perfect answer, I understand that you have to type `mixin` twice but equally for things like `internalStateMixin` it really doesn't make any sense without the suffix (so could maybe do with a better name perhaps).

**Comment by agubler** [comment]
I think we have a resolution here at least in that the mixins are currently consistently named. The mixin modules live in a mixins directory `src/mixins/Themeable` without a mixin suffix but the named exported includes the `Mixin` suffix, e.g. `ThemeableMixin`.

**Comment by agubler** [comment]
Closing, please feel free to reopen if any wants to continue the naming convention discussion.
