### ISSUE TITLE
Generate css-module-typings for cli-build pipeline

### ISSUE THREAD

**Issue by tomdye** [dojo/widget-core#275]
`css-module-typings` should be created as part of our webpack build process. Furthermore they should be included in the watch process such that they are generated as they are edited.
An attempt was made to use `typed-css-module-loader` but this was not sufficient. There are outstanding PR's and issues on this loader which may provide a solution but it's likely that we may need to create a `typescript` pre-loader which plucks out the `.css` imports and creates the appropriate typings.

**Comment by agubler** [comment]
@tomdye does this belong in widget-core?

**Comment by tomdye** [comment]
Moved to `cli-build` https://github.com/dojo/cli-build/issues/66
