### ISSUE TITLE
Remove `Messages` generic from `I18nWidget`

### ISSUE THREAD

**Issue by mwistrand** [dojo/widget-core#277]
The `I18nWidget` type takes two generics: a `Messages` type (from `@dojo/i18n`) and an `I18nProperties` type that extends `WidgetProperties`. It seems, however, that the only benefit to specifying a `Messages` generic is that it allows widgets to access their bundle messages via dot notation. As such, I propose updating the `I18nWidget` type (and `I18nMixin` interface) to the following:

```typescript
// Remove the `Messages` generic
interface I18nMixin {
    // ...
}

type I18nWidget<P extends I18nProperties> = I18nMixin & Widget<P>;
```

**Comment by mwistrand** [comment]
I see now that `WidgetState` has been removed. I will update the original description with the necessary updates.

**Comment by agubler** [comment]
@mwistrand I would say the intellisense for message bundles is extremely beneficial, why would we want to remove that support?

**Comment by mwistrand** [comment]
@ant That makes sense, so I'll close this issue.
