### ISSUE TITLE
Ability to publish single widget to npm

### ISSUE THREAD

**Issue by rishson** [dojo/widget-core#283]
Publish a widget to `npm` using the `grunt-dojo2` pipeline.
The enhancement should publish a single widget that has been through the existing `dist` process.
Questions: How will we deal with git tags?

**Comment by agubler** [comment]
@rishson Do we still need this and #178?

**Comment by agubler** [comment]
@rishson bump on the question above and whether this should be in `dojo/widgets` now?

**Comment by rishson** [comment]
Closed #178 in favour of this one.

**Comment by rishson** [comment]
Issue moved to [dojo/widgets #63](https://github.com/dojo/widgets/issues/63) via [**ZenHub**](https://www.zenhub.com/)
