### ISSUE TITLE
Call invalidate on `state:changed` event automatically

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#285]
Should the `storeMixin` hook onto the `state:changed` event and call `invalidate()` automatically or should consumers explicitly wire that functonality?

Currently just emits the event without calling invalidate.

**Comment by dylans** [comment]
Is there a use case for not wanting it to happen automatically? My guess is that most of the time you want this to happen automatically, and if you prefer to wire this functionality explicitly, you'll find a way to override.

**Comment by agubler** [comment]
I think overriding i.e. stopping the invalidation would be "hard" - however I inclined to agree that if you are using the `storeMixin` you probably want the widget to invalidate when the state has been updated.
