### ISSUE TITLE
Provide a way to remove theme classes

### ISSUE THREAD

**Issue by rorticus** [dojo/widget-core#287]
**Enhancement** 

Right now it is really convenient to add theme classes to a widget,

```ts
v('div', { classes: { ...this.theme.regularClasses, ...this.theme.conditionalClass } });
```

But there is no way to _remove_ `this.theme.conditionalClass` without manually looping over each of the classes and setting them to false.

Consider a widget with multiple children, and a "selected" child index.

```ts
this.property.children.forEach((child, index) => {
    let classes = { ... this.theme.childClass };
    if (this.properties.selectedIndex === index) {
        classes = { ...classes, this.theme.selectedClass };
    }

    return v('div', { classes });
});
```

Once the `selectedClass` is applied, it can never be removed.

Perhaps we just need a way to set all the values of a theme class to `false`?

```ts
this.property.children.forEach((child, index) => {
    let classes = { ... this.theme.childClass, toggleClass(this.theme.selectedClass, this.properties.selectedIndex === index) };

    return v('div', { classes });
});
```

**Comment by agubler** [comment]
@rorticus this should be resolved now with #311 landing.

A helper function is available on themeable widget instances, `this.classes()` which will automatically return *all* available classes for the instance set to false. so `this.classes(css.selectedClass).get()` will add the selected class and then `this.classes().get()` will remove it on a subsequent render.
