### ISSUE TITLE
Generate .ts files instead of .d.ts

### ISSUE THREAD

**Issue by tomdye** [dojo/widget-core#298]
As part of generating typings for our CSS files, we should investigate exporting them as `.ts` files rather than `.d.ts` files. 
ie.

``` typescript
export const button: string;
```

would become

``` typescript
export default {
	classes: {
		button: 'button'
	}
}
```

This would have the added bonus of working in tests without needing to require the actual css file.

**Comment by agubler** [comment]
@tomdye sounds like we can close this?

**Comment by tomdye** [comment]
Yes, I don't believe there's a benefit to this. We are revering back to a more basic `.d.ts` approach.
