### ISSUE TITLE
Make dom nodes created from `v` accessible in a widget

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widget-core#361]
At the moment the only mechanism we have for accessing a dom node is via maquette's `afterCreate` and `afterUpdate` methods which are per `v` call which is a bit clunky. We perhaps should provide a a mechanism in WidgetBase that allows you to access all dom nodes in a widget by `key`, as well as a lifecycle function on WidgetBase where you know these will be available.

**Comment by edhager** [comment]
I did some prototyping and came up with one possible solution:  https://github.com/edhager/widget-core/commit/2d24075cce5e06df856a693e0a2751800085ae26

It uses the render decorator mechanism in WidgetBase.

**Comment by edhager** [comment]
I started updating WidgetBase with code based on what was done in the prototype.  My progress is in https://github.com/edhager/widget-core/tree/widgetbase-node-lifecycle.

I have not written any tests yet.  At this point, all I know is my code compiles.

**Comment by edhager** [comment]
I added some tests and fixed some bugs.  Getting close.  I am not sure how to write a test for the afterCreate calls.

**Comment by bitpshr** [comment]
Not sure how relevant my approach is for your work, but when testing widget afterCreate calls, I pass in an object cast to `any` instead of an event, and verify certain properties or functions are called on that object.

**Comment by edhager** [comment]
I just added some update tests and there is a problem with my code.  The way I am adding the afterCreate and afterUpdate callbacks in a render decorator is giving me this error:

>Error: Functions may not be updated on subsequent renders (property: afterCreate). Hint: declare event handler functions outside the render() function.

I may have to rethink my approach.

**Comment by edhager** [comment]
I fixed the problem with the way I was registering the afterCreate and afterUpdate callbacks.  A vdom update now works.  I think I have everything working now.

https://github.com/edhager/widget-core/tree/widgetbase-node-lifecycle

**Comment by edhager** [comment]
I think my code may still have an issue.  I am storing existing afterCreate and afterUpdate callbacks in maps using properties.key as the key to the map.  That is not good enough because I think keys can be reused in different child lists.

**Comment by edhager** [comment]
I fixed the duplicate key issue.
