### ISSUE TITLE
eventHandlerInterceptor causing Maquette error

### ISSUE THREAD

**Issue by smhigley** [dojo/widget-core#397]
**Bug**

Maquette expects `eventHandlerInterceptor` to return a function (docs [here](http://maquettejs.org/docs/typedoc/interfaces/_maquette_.projectionoptions.html#eventhandlerinterceptor)), and it currently is not in: https://github.com/dojo/widget-core/blob/master/src/mixins/Projector.ts#L198

```javascript
private eventHandlerInterceptor(propertyName: string, eventHandler: Function, domNode: Element, properties: VNodeProperties) {
	// remove "on" from event name
	const eventName = propertyName.substr(2);
	domNode.addEventListener(eventName, (...args: any[]) => {
		eventHandler.apply(properties.bind || this, args);
	});
}
```

This causes a console error when `oninput` fires, because it expects the `propValue` returned by `eventHandlerInterceptor` to be defined: https://github.com/AFASSoftware/maquette/blob/master/src/maquette.ts#L483

**Comment by kitsonk** [comment]
Related to dojo/examples#196
