### ISSUE TITLE
Potential to emit more than one `projector:attached` event

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#403]
**Bug**

Currently the `ProjectorMixin` always provides an `afterCreate` upon every render.  While in practice it is unlikely that the maquette projector will recreate the root of the projector, if a render function changed the tag name of the root node of the projector for some reason, the `afterCreate` would fire again.

Ideally, the projector should clean up its afterCreate once it has fired the projector event attached and either remove the function or turn it into a no-op.

Also there is some question as to the need of having a promise that resolves upon projector attachment.

**Code**

The code in question is located [here](https://github.com/dojo/widget-core/blob/74b17eea81851f3750812e781bc9cf1c79c16d0d/src/mixins/Projector.ts#L271-L282).

**Expected behavior:**

That the projector mixin cannot logically emit duplicate attach events.

**Actual behavior:**

In theory, if maquette were to change the root node of the projector, it would call `afterCreate` again, which would issue an incorrect event.

**Comment by matt-gadd** [comment]
I believe we can now close this due to https://github.com/dojo/widget-core/pull/432 removing the need for the `projector:attached` event and `afterCreate` mechanism
