### ISSUE TITLE
Enhancements to the existing Property diffing system

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widget-core#404]
**Enhancement**

At the moment the Property Diffing system has the following mechanisms:
* per property control via the `@diffProperty($propertyName)` decorator. This allows the user to specify a custom diff function which returns a PropertyChangeRecord. This takes precedence over the catch all function.
* `diffProperties` in `WidgetBase`. This is the default catch all diff function for properties that do not have a per property control. Simple reference equality is used to determine whether a property has changed.

Because we have default behaviour for diffing, end user authors tend to presume that the diffing mechanism is sophisticated. Which so far has resulted in a few gotcha's:
* when passing functions (quite common for event handlers), if they are declared inline (or bound inline) in the `render` function, a new function will be created each render resulting in reference equality failing.
* when passing objects in a property inline in the the `render` function, once again a new object will be created per render so the reference equality will fail.
* when passing objects as a property and the same reference is used, and a value inside the object changes, reference equality is not adequate to pick up that change.

To remedy this we should consider whether we should have a default catch all behaviour at all and what that should be if it still exists. If not how can we still make it easy for the user to deal with property diffing while consciously opting-in to said behaviour.

**Comment by agubler** [comment]
My preference would be to change the default catch all behaviour for properties to do no diff'ing and require widget authors to explicitly register the properties (and the diff method) that need to be included.

This could become cumbersome/tedious when authoring widgets with lots of properties so an opt-in catch all would probably be helpful (and hopefully not abused), I think that this opt-in would leverage the `AUTO` comparator that ignores functions, shallow comparison for objects/arrays and references equality for everything else.

**Comment by rorticus** [comment]
After talking with @agubler and @matt-gadd , I think we might re-approach this.

Instead of adding a decorator,

* Make the default behavior not overridable
* Make the default behavior behave like `DiffType.AUTO`
* Change `@diffProperty` decorators so they stack, applying the base -> subclass until the property is marked as changed.
