### ISSUE TITLE
Remove `FormLabel` from Mixins

### ISSUE THREAD

**Issue by tomdye** [dojo/widget-core#405]
**Enhancement** 

As we have taken a `label` widget direction in `widgets` I believe we should now remove the`FormLabel` mixin before `beta` release to avoid confusion for early adopters.

**Comment by bitpshr** [comment]
Agreed. We really need to pull out the shared properties for form components for beta 2 though.

**Comment by agubler** [comment]
@bitpshr Agreed. Do you think it that there will be a "base" properties interface and base abstract form class that get extended? Perhaps we can raise an issue in @dojo/widgets?

**Comment by tomdye** [comment]
Yes @bitpshr , as I believe we discussed when we moved to the `label` approach. We'll identify shared properties for form fields etc... slightly further down the line such that we don't over engineer / complicate things before we need to.
