### ISSUE TITLE
Use `root` classname consistently for outermost HTMLElement of widgets

### ISSUE THREAD

**Issue by tomdye** [dojo/widget-core#407]
**Enhancement** 

Do we feel that it would be advantageous to consistently use `root` as the outermost classname for all of our dojo 2 widgets?

- Would provide a consistent way to pass `overrideClasses` to widget outer HTMLElement.
- Would lower the barrier to entry to applying classes to 'black box' widgets.
- Allows the widget author to determine the `root` element in the case of widgets such as `Dialog`
- Allows `spacing` type rules to be applied safely to a widget with greater ease.

**Example**

``` css
/* myLayout.css */
.marginClass {
   margin: 10px;
}
```

``` typescript
import * as myLayout from './myLayout.css';

/* can safely target the root class */
w(Button, { overrideClasses: { root: myLayout.marginClass } });
```

**Comment by tomdye** [comment]
@rishson  Do we feel this is `beta1` or `beta2`? I suspect the latter.

**Comment by matt-gadd** [comment]
@tomdye this is in the wrong repo no?

**Comment by tomdye** [comment]
correct, can it be moved to `widgets` or do i have to create a new one?

**Comment by tomdye** [comment]
Issue moved to [dojo/widgets #75](https://github.com/dojo/widgets/issues/75) via [**ZenHub**](https://www.zenhub.com/)
