### ISSUE TITLE
Add a `render:rendered` event?

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#409]
**Enhancement**

I have a use case where I want to *observe* what a widget actually renders.  Currently widgets emit an `render:scheduled` event, but there is no "formal" way of observing what actually gets rendered when the `__render__()` is called.

It would be good if we had something like:

```typescript
export interface RenderEventObject<W extends WidgetBase> extends EventTargettedObject<W> {
	result: VNode | string | undefined;
}
```

I also question the need of the `render:scheduled` at the moment.  I know I had originally put it in because it was something that we were struggling with getting working, but now the way the lifecycle works, it seems unnecessary.

**Comment by rishson** [comment]
@rorticus can I ask why we need this please?
I'm confused as to why we would have an event that is part of our API that is tied to a function that we have gone to lengths to 'hide'. This seems like a break in encapsulation as we are exposing the inner working of the widget auth system or at least tieing our API to it.

**Comment by dylans** [comment]
@rishson you should probably ask @kitsonk since he opened the issue, but I assume the primary reason was to make widgets easier to test...

**Comment by rishson** [comment]
👍 didn't read back far enough 😄

**Comment by kitsonk** [comment]
Further discussion with @matt-gadd and @agubler have highlighted that while there is a use case, it might not be clear and straight forward.  We should deliver #430 for now and likely need further thoughts and discussion about run-time diagnostics and debugging of which the use case for this might be needed.

**Comment by matt-gadd** [comment]
I think we should open a new issue to discuss a debugging widget-core (perhaps in the form of an extended Debugging Projector), so we can close this?

**Comment by kitsonk** [comment]
See #409
