### ISSUE TITLE
Rename d module or migrate APIs to another module

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#410]
**Enhancement**

It was pointed out at HalfStack last night, by someone seeing Dojo 2 for the first time, why we arbitrarily shortened `v` and `w`.  Of course the reason was "well we are making something like `h`" but it is true, where we have tried our best to use expressive names for things, to make it easier to grok the intent of the code, `v` and `w` sort of fall short.  Of course, upon importing things, people can destructure it into whatever they wish, but it is true that it sort of true that people coming to it for the first time might be easily confused.

Thinking about it, without overloading terms too much, would something like this make sense?

```typescript
class MyWidget extends WidgetBase<WidgetProperties> {
    render() {
        return renderDom('div', { }, [
            renderWidget(Label, { }),
            renderDom('i', { })
        ]);
    }
}
```

So `v` would become `renderDom` and `w` would become `renderWidget`.  While we know it doesn't actually render anything, it only creating objects which conform to our virtual DOM system and are lazily dealt with, the *intent* is true and ensures the end developer is making their intent more clear and is quite a bit easier for someone to *grok* what is going on.

**Comment by kitsonk** [comment]
I could also name the `d` module something more clear too, like `virtualDom` or `renderHelpers` or something more clear.

**Comment by agubler** [comment]
Whilst I can appreciate the sentiment, I think the terseness of `v` & `w` is valuable. Also as you mention these functions don't render anything so including the term render would certainly be misleading and confusing.

Lastly, yes someone who hasn't seen any documentation or tutorials perhaps wouldn't automatically know their purpose. But this is true of anything and would be true of any other name that we chose (I think both the read me and the tutorials do a good job on this).

My preference is to stay with `v` and `w`.

**Comment by kitsonk** [comment]
> Also as you mention these functions don't render anything so including the term render would certainly be misleading and confusing.

Well, technically `render()` doesn't render anything either, but that name persists, because it is easier for the developer to grok than `getVirtualDomNodes()`.  We specially changed things so it was easier for the developer to understand what to do without having to read tutorials.

Why is the terseness valuable, enough to outweigh the clarity of intent, especially when things will be shortened and mangled in production anyways?

**Comment by agubler** [comment]
Render would be hugely overloaded if we used that regardless, so therefore without debating it's use elsewhere I think for this it would be misleading and confusing.

Terness is valuable when writing code in my opinion and again the developers would not have to read the tutorials but I'd expect them to have looked at README at which point gain an understanding of their intent (quickly and easily).

And even if they didn't, I don't believe it difficult to grok the intent of `v` and `w`.

**Comment by rishson** [comment]
Its hard to name these functions to anything meaningful that does not need an explanation. I like the brevity of the current function names personally. Having slightly opaque names is actually useful in getting developers to learn and understand what these important functions do (I know that sounds counterintuitive, but I've come to believe it to be true in this instance).

However the 2 main reasons I would be against renaming is:

1) Dojo 2 users (at Sitepen) appear to have grokked these functions easily - but we should get their thoughts on the names.
2) I don't see the advantage of a rename outweighing the effort to redo all the READMEs, examples and tutorials at this stage.

**Comment by tomdye** [comment]
I can see the point the one person raised, but in that instance there is nothing to stop them from naming their import whatever they want to.

``` typescript
import { w as widgetCreationFunction } from '@dojo/widget-core/d';
```

I don't believe that anyone in the team using 'w' or 'v' has been concerned with the naming so far plus I like the fact that the function name is small as it allows me to concentrate on the widget / dom element name and the properties when I am visually grokking.

**Comment by matt-gadd** [comment]
The intent is as clear as `h`, if not clearer (`v` stands for virtualdom, `w` stands for widgets). The tersness is extremely important, this is one of the main reasons people don't use the programmatic api in react with React.createElement.

**Comment by dylans** [comment]
Probably the clearest argument I have is to rename d, as no one really uses d directly.

The argument for v, and w:

* Consistency with other HyperScript implementations
* Terseness potentially keeps very long lines of code a bit shorter
* There's no clear, relatively short name that articulates exactly what they do (best I could think of quickly would be putDom and putWidget, which is biased based on my experience with put-selector)

The argument against v, and w:

* Inconsistent with how we name things everywhere else in Dojo 2
* We have modern tooling and auto-complete so the length of the name shouldn't matter

I could argue it both ways, so it really depends what we feel is right.

I would probably dismiss the argument about React.createElement as a data point, because jsx isn't particularly terse. I think it's more that almost every example for React shows people to use and learn jsx.

**Comment by agubler** [comment]
> Probably the clearest argument I have is to rename d, as no one really uses d directly.

It's just the module name and I think that regardless of the name, consumers would need to learn about where to import `v`, `w`, `registry`, `isWNode` etc from. Perhaps `d.ts` is obscure enough to not encourage users to have preconceptions about such an critical module. 

Having said this, if we can think of a better name that doesn't include `helper` or `utils` etc and we think the benefit of the change outweighs the cost of change, I wouldn't be opposed to it.

**Comment by matt-gadd** [comment]
@dylans JSX is terse at least in the comparison we are making, because there is no call function at all (the JSX results in `React.createElement` calls). Some of the early arguments **for** JSX were explicitly around the programatic api being ugly and verbose.

```jsx
<div>
  <span>Hello World</span>
  <div>
    <span classNames="hello">Hey!</span>
    <MyWidget />
  </div>
</div>
```

```js
React.createElement(
  "div",
  null,
  React.createElement(
    "span",
    null,
    "Hello World"
  ),
  React.createElement(
    "div",
    null,
    React.createElement(
      "span",
      { classNames: "hello" },
      "Hey!"
    ),
    React.createElement(MyWidget, null)
  )
);
```

**Comment by matt-gadd** [comment]
We can't release beta1 without this issue being resolved or closed. Changing the naming of a fundamental building block of widget-core has far reaching impacts across not only code and documentation.

**Comment by kitsonk** [comment]
For clarity and expanding the examples:

What we would do now:

```typescript
class Widget {
    render() {
        return v('div', [
            v('span', 'Hello World'),
            v('div', [
                v('span', { classNames: 'hello' }, 'Hey!'),
                w(MyWidget)
            ])
        ]);
    }
}
```

Versus what is being suggested:

```typescript
class Widget {
    render() {
        return renderDom('div', [
            renderDom('span', 'Hello World'),
            renderDom('div', [
                renderDom('span', { classNames: 'hello' }, 'Hey!'),
                renderWidget(MyWidget)
            ])
        ]);
    }
}
```

**Comment by matt-gadd** [comment]
@kitsonk why is it not `renderVirtualDom`? the user maybe confused by the intent?

**Comment by matt-gadd** [comment]
Just to also expand, there is a nice symmetry at the moment between the `v` and `w` functions, their meaning and the properties they take:

`v` is shorthand for `virtualdom` which takes `VirtualDomProperties`
`w` is shorthand for `widget` which takes `WidgetProperties`

**Comment by dylans** [comment]
I'd say a better example to see what this looks like at bigger scale would be the Dialog example:

```ts
render() {
	return v('div', [
		w(Dialog, {
			key: 'dialog',
			title: 'Dialog',
			open: <boolean> this.state['open'],
			modal: <boolean> this.state['modal'],
			underlay: <boolean> this.state['underlay'],
			closeable: <boolean> this.state['closeable'],
			onRequestClose: () => {
				this.setState({ open: false });
			}
		}, [
			`Lorem ipsum dolor sit amet, consectetur adipiscing elit.
			Quisque id purus ipsum. Aenean ac purus purus.
			Nam sollicitudin varius augue, sed lacinia felis tempor in.`
		]),
		v('button', {
			id: 'button',
			innerHTML: 'open dialog',
			onclick: this.openDialog
		}),
		v('div', { classes: { option: true }}, [
			v('input', {
				type: 'checkbox',
				id: 'modal',
				onchange: this.toggleModal
			}),
			v('label', {
				for: 'modal',
				innerHTML: 'modal'
			})
		]),
		v('div', { classes: { option: true }}, [
			v('input', {
				type: 'checkbox',
				id: 'underlay',
				onchange: this.toggleUnderlay
			}),
			v('label', {
				for: 'underlay',
				innerHTML: 'underlay'
			})
		]),
		v('div', { classes: { option: true }}, [
			v('input', {
				type: 'checkbox',
				id: 'closeable',
				onchange: this.toggleCloseable,
				checked: true
			}),
			v('label', {
				for: 'closeable',
				innerHTML: 'closeable'
			})
		])
	]);
}
```

vs.

```ts
render() {
	return renderVirtualDom('div', [
		renderWidget(Dialog, {
			key: 'dialog',
			title: 'Dialog',
			open: <boolean> this.state['open'],
			modal: <boolean> this.state['modal'],
			underlay: <boolean> this.state['underlay'],
			closeable: <boolean> this.state['closeable'],
			onRequestClose: () => {
				this.setState({ open: false });
			}
		}, [
			`Lorem ipsum dolor sit amet, consectetur adipiscing elit.
			Quisque id purus ipsum. Aenean ac purus purus.
			Nam sollicitudin varius augue, sed lacinia felis tempor in.`
		]),
		renderVirtualDom('button', {
			id: 'button',
			innerHTML: 'open dialog',
			onclick: this.openDialog
		}),
		renderVirtualDom('div', { classes: { option: true }}, [
			renderVirtualDom('input', {
				type: 'checkbox',
				id: 'modal',
				onchange: this.toggleModal
			}),
			renderVirtualDom('label', {
				for: 'modal',
				innerHTML: 'modal'
			})
		]),
		renderVirtualDom('div', { classes: { option: true }}, [
			renderVirtualDom('input', {
				type: 'checkbox',
				id: 'underlay',
				onchange: this.toggleUnderlay
			}),
			renderVirtualDom('label', {
				for: 'underlay',
				innerHTML: 'underlay'
			})
		]),
		renderVirtualDom('div', { classes: { option: true }}, [
			renderVirtualDom('input', {
				type: 'checkbox',
				id: 'closeable',
				onchange: this.toggleCloseable,
				checked: true
			}),
			renderVirtualDom('label', {
				for: 'closeable',
				innerHTML: 'closeable'
			})
		])
	]);
}
```

or something like:

```ts
render() {
	return putDom('div', [
		putWidget(Dialog, {
			key: 'dialog',
			title: 'Dialog',
			open: <boolean> this.state['open'],
			modal: <boolean> this.state['modal'],
			underlay: <boolean> this.state['underlay'],
			closeable: <boolean> this.state['closeable'],
			onRequestClose: () => {
				this.setState({ open: false });
			}
		}, [
			`Lorem ipsum dolor sit amet, consectetur adipiscing elit.
			Quisque id purus ipsum. Aenean ac purus purus.
			Nam sollicitudin varius augue, sed lacinia felis tempor in.`
		]),
		putDom('button', {
			id: 'button',
			innerHTML: 'open dialog',
			onclick: this.openDialog
		}),
		putDom('div', { classes: { option: true }}, [
			putDom('input', {
				type: 'checkbox',
				id: 'modal',
				onchange: this.toggleModal
			}),
			putDom('label', {
				for: 'modal',
				innerHTML: 'modal'
			})
		]),
		putDom('div', { classes: { option: true }}, [
			putDom('input', {
				type: 'checkbox',
				id: 'underlay',
				onchange: this.toggleUnderlay
			}),
			putDom('label', {
				for: 'underlay',
				innerHTML: 'underlay'
			})
		]),
		putDom('div', { classes: { option: true }}, [
			putDom('input', {
				type: 'checkbox',
				id: 'closeable',
				onchange: this.toggleCloseable,
				checked: true
			}),
			putDom('label', {
				for: 'closeable',
				innerHTML: 'closeable'
			})
		])
	]);
}
```

I guess my point is that it feels less verbose the most involved the example gets (and as the ratio of things beyond simply creating a DOM node increases.

**Comment by tomdye** [comment]
I think the longer function names are too noisy @dylans and detract from the tag / widget name: `div` `label` `Button` etc. That's the part which is more important to me, let's not forget that initially we had `d` which did both widgets and virtual dom. The function name / type itself is unimportant in my opinion.

**Comment by bitpshr** [comment]
JSX has a subtle but existent learning curve. I think the learning curve around the naming of `v` and `w` is far less. I like the terseness because it's in line with what popular virtual DOM libraries do, and as @tomdye pointed out, it adds focus to the tag names rather than the function calls.

**Comment by mwistrand** [comment]
After reading through the readme, it was not difficult to understand `v` or `w`, and I did not find myself confusing the two or wishing I could use a different tool for the job. I personally would prefer to not rename them. As an alternative, there's no reason we couldn't export aliases with more descriptive names:

```typescript
export function v() { ... }
export const renderVirtualDom = v;

export function w() { ... }
export const renderWidget = w;
```

**Comment by devpaul** [comment]
Clean Code says that the more common a function is and the larger its scope the more terse its naming should be. Conversely the least used functions with the smallest scope should have the longest names (e.g. private class methods). The opposite is true for variables (e.g. `i`).

If `v` and `w` are used throughout as a staple of the framework then they should be ok with a short name. Naming `w()` something like `registerWidgetWithProjectorForRenderingStuff()` would be totally wrong. My only (small) concern is one letter names could collide with naming for working with matrices. From what I've read above, `d` may require renaming because it isn't as commonly used or used in as wide of scope.

**Comment by agubler** [comment]
@devpaul `d` is just the module name (that exports `v` and `w` plus others) not a function.

**Comment by pottedmeat** [comment]
I was going to respond with basically what @mwistrand said - exporting aliases seems like a good way to handle it. It would be especially effective for the documentation to say "v is an alias of virtualDom" and "virtualDom is an alias of v".

I do think that having the module named d could be changed - it contains a lot of interrelated stuff that I think having a name that describes those commonalities would be helpful.

**Comment by agubler** [comment]
Don't forget users can alias them on import too.

**Comment by pottedmeat** [comment]
Yeah, I had thought about that but my experience with automatic imports would make it so that I'd want to type `v` and have it import `v`. I was thinking the aliases would be useful just for documentation or for users who crave verbosity.

**Comment by msssk** [comment]
I put a high value on having a friendly API, so I think it's worth incurring any incidental work (e.g. updating docs) in order to ensure we have a good API. That said...

When I got started with Maquette and Dojo 2, I did not like `h`, `v`, or `w`. However, it didn't take too much time working with code to appreciate them. I think @dylans's examples and @devpaul's comment do a good job of demonstrating that `v` and `w` are good choices. And fortunately there's aliases for those who strongly disagree.

`d` could do with a better name.

**Comment by kitsonk** [comment]
I disagree with the aliases...  Mainly because we would be exporting something that we would never use in our examples, and people might discover the alias, but since we would really *care* about it, it could easily lead to confusion.  Destructuring assignment is always available for those people who want to follow a different model and there are no aliases to maintain for us.

It sounds like the only thing that is widely agreed on is that `d` is not the best name for the module and `v` and `w` need to be either folded into another module with a more expressive name or we need to rename the module.  I have changed the title of the issue to reflect that.

**Comment by edhager** [comment]
I think "d" is a bad name because of the TypeScript practice of defining interfaces for modules implemented in JavaScript in files named [something].d.ts.  When I started using dojo2, I was surprised to find the implementations of `v` and `w` in d.ts.  

I like Neil's suggestion of using "authoring.ts": `@dojo/widget-core/authoring`.

**Comment by kitsonk** [comment]
We have had quite a bit of feedback on this, and quite a bit of usage, and while it is terse and potentially confusing, it doesn't really impede usage.  In addition we have the alternative syntax of TSX/JSX if people really want.  Therefore I feel this is unactionable at this point in time.
