### ISSUE TITLE
animations/cssTransitions does not support jsdom

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#412]
**Bug**

It is difficult to unit test widgets against jsdom because `animations/cssTransitions` assumes that the environment does not properly support animations.

**Comment by sebilasse** [comment]
@kitsonk @dylans – I can't server side render anymore. 
The primary reason for me is the `import 'pepjs';` in `widget-core/src/mixins/Projector.ts` ...
Rendering on the server is very important to me because

> “If it’s not curlable, it’s not on the web.”
http://tantek.com/2016/311/t3/js-dr-in-print

**Comment by kitsonk** [comment]
@sebilasse take a look at https://github.com/dojo/test-extras/blob/master/src/support/loadJsdom.ts

Obviously if you aren't just testing, you might not want to use that module directly but adapt it to meet your needs.  It also uses jsdom v10.  If you are still on previous versions, previous commits to this module should show you how to do it.

In particular your issue with pep is addressed on [this line](https://github.com/dojo/test-extras/blob/d4a4d7c3731d435afeccfec213a31ead9c3c84da/src/support/loadJsdom.ts#L52).

It should patch everything to allow Dojo 2 to work under jsdom.  I think we can actually close this issue because `widget-core` now uses this module to load it for unit tests.

**Comment by kitsonk** [comment]
For this issue, we need to migrate from [the internal loadJsdom](https://github.com/dojo/widget-core/blob/62a818396095be143118ea0bfa37b7b83e42aa7b/tests/unit/all.ts#L1) to the one included in `@dojo/test-extras`.

**Comment by sebilasse** [comment]
@kitsonk 
Really appreciate your response. Anything works again within an hour.

What if `ProjectorMixin` would take an extra argument, a (e.g. jsdom) `window` - and optionally use it in favour of global - wouldn't it prevent cluttering up the global namespace ?
Currently `pepjs` is the only dependency needing `(window === global)` - just a thought.

Thank You !
btw : 

> If you are still on previous versions ...
:: always up to date and trying to to keep the beta pace

**Comment by kitsonk** [comment]
Actually [maquette](https://github.com/AFASSoftware/maquette/blob/master/src/maquette.ts) looks for a global `document` and there are a few other places in `widget-core` that expect `document` as well.  Obviously we can clean up `widget-core` but I am not sure how much the they would be interested in taking the upstream changes.  Right now, we only use it for testing.  While server side rendering was one of the use cases that drew us to a virtual DOM, we really haven't considered all the ramifications of supporting that at this point.

I have opened #473 for that.

> always up to date and trying to to keep the beta pace

I did mean jsdom.  v10 was a significant API change only a couple days ago.  If you are doing heavy jsdom stuff.

**Comment by sebilasse** [comment]
I see - jsdom is 9.12 - using `loadJsdom` with minor changes now

```TypeScript
import global from '@dojo/core/global';
import { add as hasAdd, exists } from '@dojo/has/has';
import { VirtualConsole } from 'jsdom';

/* In order to have the tests work under Node.js, we need to load JSDom and polyfill
 * requestAnimationFrame */

declare global {
	interface Window {
		CustomEvent: typeof CustomEvent;
		CSSStyleDeclaration: typeof CSSStyleDeclaration;
	}
}

/**
 * If `jsdom` loads, this is a reference to the virtual console for the global `window` and `document`
 */
export let virtualConsole: VirtualConsole | undefined;

/* Create a basic document */
let doc: Document;

if (!('document' in global)) {
	const jsdom = require('jsdom'); /* Only attempt to load JSDOM to avoid using a loader plugin */
	/* create a virtual console and direct it to the global `console` */
  if (!!jsdom.createVirtualConsole) {
    virtualConsole = jsdom.createVirtualConsole() as VirtualConsole;
  	virtualConsole.sendTo(console);
  } else if (!!jsdom.VirtualConsole) {
    virtualConsole = new jsdom.VirtualConsole() as VirtualConsole;
    virtualConsole.sendTo(console);
  }
	/* Create a new jsdom instance */
	const dom = new jsdom.jsdom(`
		<!DOCTYPE html>
		<html>
		<head></head>
		<body></body>
		<html>
	`, {
		virtualConsole,
		runScripts: 'dangerously'
	}).defaultView;

	/* Assign a global window */
	global.window = dom.window;

	/* Assign a global document */
	doc = global.document = global.window.document;

	/* Assign a global DocParser */
	global.DOMParser = global.window.DOMParser;

	/* Needed for Pointer Event Polyfill's incorrect Element detection */
	global.Element = global.window.Element;

	/* Patch feature detection of CSS Animations */
	Object.defineProperty(
		window.CSSStyleDeclaration.prototype,
		'transition',
		Object.getOwnPropertyDescriptor((<any> window).CSSStyleDeclaration.prototype, 'webkitTransition')
	);

	/* Polyfill requestAnimationFrame - this can never be called an *actual* polyfill */
	global.requestAnimationFrame = (cb: (...args: any[]) => {}) => {
		setImmediate(cb);
		// return something at least!
		return true;
	};

	global.cancelAnimationFrame = () => {};

	hasAdd('jsdom', true);
} else {
	doc = document;
	/* istanbul ignore else */
	if (!exists('jsdom')) {
		hasAdd('jsdom', false);
	}
}

export default doc;
```

**Comment by sebilasse** [comment]
@kitsonk Unfortunately the import css part does not work yet with jsdom but it is needed for statements like this.classes() 

```
/Users/sebi/Desktop/redaktorTS2/_build/src/Template/w/styles/worker.css:1
(function (exports, require, module, __filename, __dirname) { .worker {
SyntaxError: Unexpected token .
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/sebi/Desktop/redaktorTS2/_build/src/Template/w/widgets/Worker.js:27:15
```

**Comment by kitsonk** [comment]
@sebilasse this gets into really complex build process steps, not anything to do with jsdom, I believe.  It should be actually trying to load `w/styles/worker.css.json` which is the map of localised CSS names which are then put into the modules so the right class names are added to the virtual DOM.  With `@dojo/cli-build` this is done via a [WebPack plugin](https://github.com/dojo/cli-build/blob/31ba670f1c0846a45bac3a5f20fbf3a3e21e4e34/src/webpack.config.ts#L259).  With our package builds, like `@dojo/widgets` this is done as part of the [grunt build tasks](https://github.com/dojo/grunt-dojo2/blob/master/tasks/util/postcss.ts#L23-L29).  There is also an example of how this is generated and injected in a page in [`@dojo/web-editor`](https://github.com/dojo/web-editor/blob/master/src/support/css.ts#L78-L119).

**Comment by sebilasse** [comment]
@kitsonk FYI

I think I have also resolved the CSS part serverside. 
It is ridiculous easy because CSS modules got you covered. Particularly it was

```
// teaches node.js to load css files 
require('css-modules-require-hook/preset');
```
from [and this is exactly what I needed] : https://github.com/css-modules/css-modules-require-hook

This is not covered in cli-build (yet) - should I open an issue? (I totally understand that SSR is a "next step" anyway) - however

I will now start to move the stuff into my template engine for express.
Because if node.js has got the correct language (https://github.com/dojo/widget-core/issues/523) and if I use CSS as above I do not need to "build" any dojo-app - it could be done by the template engine.

The `projector` would be cached 
if you call my .compile() or 
if you call my .render() for the first time.

Any subsequent my .render() would call `projector.setProperties` ...

**Comment by kitsonk** [comment]
This issue sort of meandered all over the place.  Right now, our configuration of JSDom is not impeding our ability to test and we will tackle SSR under separate issues in the future.

**Comment by kitsonk** [comment]
This has an associated PR.  Adding to the SSR epic and re-opening.

**Comment by agubler** [comment]
Closing as issue is outdated and associated PR was also closed.
