### ISSUE TITLE
Rename overrideClasses to something more appropriate

### ISSUE THREAD

**Issue by tomdye** [dojo/widget-core#428]
**Enhancement** 

`overrideClasses` is not really an appropriate name for the functionality it provides. We should look at changing this to something more semantically correct.
The actual functionality is additive, so `additionalClasses` may be a more appropriate name. 

I'm aware that this is a breaking change, but we have already had one concern from a user on this naming.

Please suggest a better name / thoughts via comments.

**Comment by tomdye** [comment]
Should be completed along with https://github.com/dojo/widgets/issues/75 as they are generally used together as a predictable was to target the root node.

**Comment by bitranch** [comment]
I suggested `additionalClasses` in gitter. That remains the best fit that I've thought of.

**Comment by tomdye** [comment]
We have came up with the name `extraClasses`. Anyone opposed?

**Comment by bitranch** [comment]
`extraClasses` is shorter and still says what it does. Works for me.
