### ISSUE TITLE
API Doc Review for widget-core

### ISSUE THREAD

**Issue by eheasley** [dojo/widget-core#441]
Review the generated API documentation for `widget-core` at http://dojo.io/api/. If any of the information is not accurate, please make the necessary adjustments to the API documentation within this repo.

**Comment by sebilasse** [comment]
Regarding the documentation there is a point I was not able to understand : `ThemableMixin` :
Probably I need to create a similar Mixin with postcss but I am not sure ...

Whenever I used "CSS modules" before I used http://postcss.org with https://github.com/css-modules/postcss-modules -
that gave me 
1) a JSON mapping for the scoped/"locale" classes and 
2) the processed CSS, e.g.
`
var source = fs.readFileSync(DCSS, 'utf8').toString();
postcss([autoprefixer, postcssModules]).process(source, { from: attribs.href })
                            .then(function (result) { console.log('POSTCSS', result.css); });
`

The server could then also precompile the CSS (e.g. jsDom as described in https://github.com/dojo/widget-core/issues/412).

The `ThemableMixin` seems to give me only one part 1), the mapping.
How could I get the according CSS definitions?
