### ISSUE TITLE
Support multiple widget registries?

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#457]
**Enhancement**

Should widget-core support multiple registries over the existing local and global registries? Would they be useful? What would the use case be?

Related to #453

**Comment by dylans** [comment]
Any chance you could summarize the background info on registries and their use cases currently, in order to facilitate useful feedback?

**Comment by agubler** [comment]
Closing, a single registry can be passed explicitly and a default registry will be passed along with it (once #636 is completed)
