### ISSUE TITLE
README: Change `overrideClasses` to `extraClasses`

### ISSUE THREAD

**Issue by bitranch** [dojo/widget-core#462]
**Bug**

Package Version: beta1

**Expected behavior:**

The `overrideClasses` property was renamed `extraClasses` in the code. However the README hasn't been updated to match that. For example, in the _theming_ section it still says:

```
Instead you must use the overrideClasses property ...
```

All references to `overrideClasses` in the README should be replaced with `extraClasses` in both text and examples.

**Comment by agubler** [comment]
Thanks @bitranch, we'll get that updated before the next release.
