### ISSUE TITLE
Feature Request: Support "safer" server side rendering

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#473]
**Enhancement** 

We should consider full abstracting `widget-core` and dependencies from the global `document` in order to make server side rendering easier.  The project could ascend its root node to find the appropriate reference to the document it should be using, instead of grabbing the global one.

Refs #412

**Comment by matt-gadd** [comment]
I think we can go ahead and close this, when we do support SSR properly we will likely add a fast path to avoid dom all together
