### ISSUE TITLE
widget-core README property differences

### ISSUE THREAD

**Issue by edhager** [dojo/widget-core#488]
The widget-core README "The 'properties' lifecycle" section jumps right into how to configure property differencing without any explanation of why there is property difference checking in widgets.  There needs to be a better description of why the properties lifecycle exists.  Give an overview of what the properties lifecycle is doing.

**Comment by agubler** [comment]
The readme has changed significantly since May, closing this for now - We can reopen an issue if there are still gaps to be filled.
