### ISSUE TITLE
Remove `bind` from the `v` and `w` properties interfaces

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#499]
**Enhancement**

Currently it is possible to provide a custom `bind` value via both the `v` and `w` properties, if no `bind` value is passed then the scope of the enclosing widget is assumed and automatically set.

Being able to pass an arbitrary scope via `bind` is confusing and will lead to complexities when trying to reason about widget behaviour, the proposal is to remove `bind` from the interfaces and always automatically bind functions to the scope of the widget that the `v` or `w` is defined.

This will be especially helpful when passing children via the 3rd argument of `v` and `w` as this currently requires a bind value to be passed in order to correctly define bind to the correct scope.

**Comment by kitsonk** [comment]
Is this likely to be a breaking change?  I assume you would want to _ban_ it versus just making it lazy as it is now.  A quick look at [widgets shows](https://github.com/dojo/widgets/search?utf8=%E2%9C%93&q=bind&type=) shows that the only uses of it are to do `this` anyways.  I agree with the logic that users of `v()` and `w()` shouldn't concern themselves about it, and there are other ways to bind things if they have an extra-ordinary case.

**Comment by agubler** [comment]
@kitsonk Yes you are correct, this will be a breaking change (I have added the correct label) as consumers will need to update their widgets to not pass `bind` as it will be removed from the API.

Then bind will automatically be added for the containing widget within widget-core.

**Comment by agubler** [comment]
So it won't be a breaking change functionality wise, but just on the need to remove the current uses of `bind`.
