### ISSUE TITLE
Update beta1.4 -> beta1.5 causes multiple errors

### ISSUE THREAD

**Issue by sebilasse** [dojo/widget-core#513]
What happened?
All I did was updating the @dojo node_modules to the recent versions but now all my widgets have errors like in the screenshot and the file widget-core/interfaces shows so many errors that in Atom TS quits unexpectedly. What could I do?

<img width="1040" alt="bildschirmfoto 2017-05-17 um 13 07 22" src="https://cloud.githubusercontent.com/assets/750300/26151308/80994926-3b02-11e7-898f-e2f99a692364.png">

**Comment by agubler** [comment]
@sebilasse Which version of typescript are you using? It looks like it could be because widget-core needs typescript 2.3.2.

**Comment by sebilasse** [comment]
@agubler Using 2.4

**Comment by agubler** [comment]
So using the `next` tag from TypeScript? Does the project compile with `./node_modules/.bin/tsc`?

**Comment by sebilasse** [comment]
@agubler just a second. Basically tons of the Errors might depend on the first one : "WidgetBase requires 4 type arguments"

**Comment by agubler** [comment]
That looks like an error from a TS version that doesn't support default generics (which is why I thought it could be the TS version.)

**Comment by sebilasse** [comment]
It `tsc` compiles with warnings, not more info than above, only maybe

```
node_modules/@dojo/widget-core/WidgetBase.d.ts(140,26): error TS2304: Cannot find name 'Readonly'.
````

**Comment by agubler** [comment]
Can you double check the `tsc` version by running `tsc --version`? because `Readonly` was introduced in TS2.1.0.

**Comment by sebilasse** [comment]
@agubler Yes. I see and thought so. 
But it is really saying `Version 2.4.0-dev.20170517` (globally installed) -
OK, figured out - there is also a local version 2.1 which seems to be specified in a dependency I am using...
From the command line : Can I force `tsc` to use the global version to confirm this ?

**Comment by agubler** [comment]
I would add typescript to your `package.json` specifying the version you need (`2.3.2` or the `next` tag if you need it).

Then re-install your node modules?

**Comment by sebilasse** [comment]
@agubler Just did that - it is fine now. It was not related to dojo at all. Sorry for the confusion.

**Comment by sebilasse** [comment]
Colleague just told me that the issue comes from the typescript dependency which every new
`dojo create` is installing.
From the package.json it is currently `~2.2.1`

**Comment by agubler** [comment]
@sebilasse I'd recommend upgrading `@dojo/cli-create-app`, the latest release `2.0.0-beta1.3` uses `~2.3.2`.

**Comment by sebilasse** [comment]
@agubler @dylans  What would be the most convenient way to update dojo2 then ?
With dojo1 I replaced a single folder ...

With dojo2 it was a bit horrible
- npm updated each dojo packages in node_modules in my already built apps (can I say dojo build to not npm i but use higherlevel node_modules ?)
- npm updated each global dojo packages for CLI
- npm updated each dojo packages in the root of my project (where dojo and other stuff come together)

**Comment by agubler** [comment]
@sebilasse To upgrade Dojo 2 you'll need to do so in each Dojo 2 project. If you are targeting a tag, for example `beta1` or `latest` then you simply running `npm i` in each project will ensure that the dependencies are updated the latest version against the tag. 

If you are targeting specific versions such as `>=2.0.0-beta1.2` you'd need to remove the `node_modules` directory and then run `npm i` to ensure that the latest versions that satisfies the `package.json` is used.

To update `@dojo/cli`  you should just be able to do `npm i @dojo/cli -g` to get the current `latest` or `npm i @dojo/cli@beta1 -g` if you want the latest `beta1` release (they should be the same).

I hope that helps! Let me know if there is anything else I can help with!

**Comment by sebilasse** [comment]
@agubler Well it takes very long. That would also mean if I would have one webpage with 10 dojo apps (e.g. the "building JS blocks" I am writing for indieweb) it would be > 1GB which is a bit scary.

And off course the above mentioned would work only in theory for now because it is based on microformats which can only work if html is sent from the server to the client (the way the internet was designed to work once).

However :
It would be fine if I could _either_ be able to build a dojo app and get the CSS mapping somewhere so that the server could apply the correct classes (+locales) - I am not sure if it is related to some of these errors (if I `dojo build`)

<img width="605" alt="bildschirmfoto 2017-05-26 um 17 10 43" src="https://cloud.githubusercontent.com/assets/750300/26500780/8c1f87a6-4237-11e7-9af3-001c23dcf024.png">

_or_ if I could make any webcomponent work with `--element` - this is giving no error in the browser but it seems the JS of the imported component is not executed at all ...

**Comment by dylans** [comment]
@sebilasse perhaps we can open a separate issue in dojo/meta around better documentation for upgrading projects efficiently, so that your feedback isn't lost in this issue?
