### ISSUE TITLE
afterRender Decorators returning undefined

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#522]
**Enhancement**

The `afterRender` method decorator currently allows you to use it to decorate a method that doesn't return a `DNode`, so someone can quite easily mis-use the decorator and not return anything which causes a run-time exception.  (I am not going to say how I found this out).

We should consider if there is any way to guard against decorating methods that don't conform to the required API, or consider that if the method returns `void` that the original `DNode` is used.  There are potentially legitimate use cases of wanting to perform an activity after the render that doesn't require a return of the `DNode`.  This would also allow someone to just modify the source `DNode` without having to return it.

**Comment by agubler** [comment]
@kitsonk I'm not sure how we can correctly enforce the function interface for the the decorator.

But we can certainly error/warn when the nodes are not returned from the `afterRender` decorator and also the same for the `beforeRender` decorator.

Both of these could also then just the original argument for a void return.
