### ISSUE TITLE
Add invalidation capability to Injector

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widget-core#527]
**Enhancement**
The majority of times you are using an Injector, it is to inject something from a context to a Widget when something in the context changes. 

At the moment if something changes its impossible to cause an `invalidation` for these changes to propagate without extending the `BaseInjector`. It would be nice if we had a mechanism that the BaseInjector provides to invalidate, so we don't have to extend.

**Comment by agubler** [comment]
What do you think to enforcing the context to be an `Evented` class, and then in the base injector listening to an event from the context to cause the widget to invalidate. This is what was done for the theme injection.
