### ISSUE TITLE
Flow CSS Module comments through to typings

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#530]
**Enhancement**

While this isn't strictly part of `widget-core` we currently recommend [`typed-css-modules`](https://www.npmjs.com/package/typed-css-modules) to generate typings for CSS Modules and typings for CSS modules is an overall concern of `widget-core`.

It would be good if we had a way to flow CSS comments through to the CSS module typings.  This would allow a CSS Module author to provide intellisense in the IDE for styles.  This could be accomplished by raising a feature request or PR with `tcm`.

An example, given the following CSS:

```css
/**
 * A base class for a widget
 */
.base {
  font-size: 48px;
}
```

Would result in a `.d.ts` of:

```ts
/**
 * A base class for a widget
 */
export const base: string;
```

**Comment by agubler** [comment]
Creating definition files for css modules does not happen in widget-core.
