### ISSUE TITLE
Cannot add children to a Custom Element after creation

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widget-core#531]
**Enhancement**
If you create a custom element then add children post creation, they are not consumed into the parent. We can achieve this using a `MutationObserver` to watch for child nodes.

**Comment by kitsonk** [comment]
That would give us the changes, but another consideration is what to do with the DOM after that.  Re-using DOM after the projector is created would be tricky I suspect, so it would be easier to detach those children from the DOM, generate the virtual DOM nodes necessary and then invalidate.

**Comment by matt-gadd** [comment]
@kitsonk we already do those things via the `DomWrapper`. basically we just need to take the children nodes, wrap them and set them as children (we already do this at the initialisation phase)

**Comment by kitsonk** [comment]
This is flagged as expedited but hasn't been actioned.  Is this still required, and if so, when?

**Comment by kitsonk** [comment]
Need to do something with this or close it.
