### ISSUE TITLE
Consider supporting an array of DNodes being returned from render

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widget-core#533]
**Enhancement** 
It would be nice for widgets to be able to return an array of `DNodes` from a `render` call. This would allow authors to say create a container widget that creates a number of `li` elements, but don't have to create the outer `ul` element.

**Comment by agubler** [comment]
I agree that this would be a nice enhancement. For a projector, multiple children would need to be wrapped. We should detect this in the projector and provide the wrapping node (probably a `div`)
