### ISSUE TITLE
Styles applied via extraClasses are not themeable

### ISSUE THREAD

**Issue by tomdye** [dojo/widget-core#537]
**Discussion** 

Package Version: current

The classes passed to child widgets using `extraClasses` are not themeable. 
This is not a bug per-say but a discussion point. The problem is that they are passed directly to the widget and bypass the code in `Themeable` that decides which theme classes to use. As such, any classes passed via `extraClasses` should be considered to be `fixed`.

Do we think this is the right approach?
Do we agree that using `extraClasses` for anything other than positioning is an anti pattern?

**Comment by tomdye** [comment]
My personal opinion is that anything other than `extraClasses: { root: 'myPosititioningClass' }` is an anti pattern and should be avoided. 
If the developer is attempting to change visual styles / hide elements then these should likely be moved to widget level properties to control the behaviour. Alternatively, in these cases it may be more appropriate to create smaller widgets themselves which can be themed appropriately.

**Comment by agubler** [comment]
@tomdye who would it be good to get to weigh in on this discussion? @smhigley? @bitpshr? Others?

**Comment by smhigley** [comment]
After chatting with @tomdye I see his point that it would break style encapsulation to use `extraClasses` for theming. I'm fine with extending widgets when it's necessary to re-theme them.

**Comment by tomdye** [comment]
Glad you're in agreement @smhigley . @bitpshr any thoughts? Be good to get this cleared away.

**Comment by bitpshr** [comment]
I agree that `extraClassses` shouldn't be used for theming, and I never understood them to be used in that way. Good by me.

**Comment by sebilasse** [comment]
@tomdye Yes, also agreed 

> that extraClassses shouldn't be used for theming, and I never understood them 

;) The purpose of `extraClasses` is not entirely clear to me :

A user using dojo widgets might want to apply global classes to any widget from a CSS which is not related to any widget.
Is this what `extraClasses` is intended for ?
Does a widget author has to take care of this, is there a convention or should it be the same in `w` than in `v` ?

My feeling is that this property naming should be the same for each dojo2 widget.
Would it be `extraClasses` or `classes` then and `class` in webcomponents ?
React uses `className`/`class`.

Currently I am using it like
`classes: this.classes(...rootClasses).fixed(className)` where className is set from the consumer of the widget ...
Now I wonder if this is correct and if the name of `this.properties.className` could be the same for all widgets (either in dojo/widgets too and/or in WidgetBase)

**Comment by tomdye** [comment]
@sebilasse take a look at https://github.com/dojo/widget-core#overriding-theme-classes.
Documentation might need a little update but you should be able to get the gist from there. widgets should have a `root` class and most of the time this is the only one `extraClasses` is likely to target in order to position a child within a parent element.

**Comment by sebilasse** [comment]
@tomdye 
Sorry. It seems I can't explain it properly...
My question is basically what is the 🐉-equivalent for [React's](https://facebook.github.io/react/docs/dom-elements.html) `className` which is any classes without any associated CSS - basically not 'overriding' but 'non scoped extending' ...

**Comment by matt-gadd** [comment]
React doesn't have a specific property at a component level (it's up to the author to consume a prop then apply it to className) and it's the same for widgets in Dojo 2. The item you're linking to is for dom nodes only. The equivalent would be using `v` and `classes`.

**Comment by agubler** [comment]
@tomdye @bitpshr @smhigley Is there any action required from this issue? Or can it be closed?

**Comment by agubler** [comment]
Closing this issue as I believe a consensus has been reached regarding the styling of `extraClasses`. Please reopen if there is any further action to be taken.
