### ISSUE TITLE
Document DomWrapper in the README

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#545]
**Bug** 

We are missing any documentation of the DomWrapper in the README.

**Comment by sebilasse** [comment]
@kitsonk @dylans – a question : 

A user using dojo widgets might want to apply global classes to any widget from a CSS which is not related to any widget.
Does a widget author has to take care of this, is there a convention or should it be the same in `w` than in `v` ?

My feeling is that this property naming should be the same for each dojo2 widget.
Would it be `classes` then and `class` in webcomponents ?
React uses `classNames`/`class`.

**Comment by agubler** [comment]
@kitsonk are you still intending on taking this one?
