### ISSUE TITLE
Duplicate imported modules for DomWrapper

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#549]
**Bug**

[Line 2](https://github.com/dojo/widget-core/blob/3815934e47054db59ac999139e06f0f43823d8b8/src/util/DomWrapper.ts#L2) and [Line 5](https://github.com/dojo/widget-core/blob/3815934e47054db59ac999139e06f0f43823d8b8/src/util/DomWrapper.ts#L5) are importing from the same module:

```ts
import { WidgetBase } from './../WidgetBase';
import { WidgetProperties, VirtualDomProperties } from './../interfaces';
import { v } from './../d';
import { VNode } from '@dojo/interfaces/vdom';
import { Constructor } from '../interfaces';
```

**Comment by agubler** [comment]
fixed by #548
