### ISSUE TITLE
DomWrapper has issues with certain VirtualDomProperties

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#553]
**Bug**

Some of the `VirtualDomProperties` cause issues with maquette when they are detected in `DomWrapper` properties (e.g. `classes`).

**Comment by sebilasse** [comment]
> e.g. classes
That makes some things clear to me ;)

It is called `className` in React which is misleading to me because it should be plural.
https://facebook.github.io/react/docs/dom-elements.html

Q:
If any user wants to specify any "global" class for the root of a `w` widget, what would the property be  ?
