### ISSUE TITLE
Make properties mandatory for `v()`

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#558]
**Enhancement**

Due to the fact that all the properties on `VirtualDomProperties` are optional TypeScript does not correctly enforce the children types correct when passed as the second argument. As effectively `VirtualDomProperties` accepts an array object that doesn't match the `children` contract that we then still use this object for children... doh.

We should consider making `properties` mandatory for `v()`, it would mean consumers would have to pass `{}` but it would remove a potential for covering a design time development error.

Plus it would then be symmetrical with `w()`.

**Comment by tomdye** [comment]
Sounds sensible to me

**Comment by agubler** [comment]
This is annoying because the `VirtualDomProperties` interface will still allow `[ v(...), v(...) ]` as the second argument without any design time warning/error which means users are still as likely to fall into a trap. Plus makes finding all the occurrences downstream where children is being passed as the second argument difficult and prone to error.

**Comment by sebilasse** [comment]
@agubler 
Why not make `properties` optional for `w` as well ?
I do not see any sense in always delivering empty objects where they are not needed.
With my `semantic ui dojo2 widgets` I often write :
w(Container, {}, [ ...myChildren ])
because if a container is not 'fluid' or 'text' properties are always empty !

**Comment by agubler** [comment]
@sebilasse because doing that with `w` causes issues guarding the properties types where there are mandatory propertues due to it being a generic. In fact we actually previously made a change to align `w` and `v` and subsequently backed it out (https://github.com/dojo/widget-core/pull/468)

**Comment by agubler** [comment]
Closing this due to the complexities mentioned above and with the impending support for "Weak Types" in TS2.4
