### ISSUE TITLE
Abstract the real DOM from the Virtual DOM

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#559]
**Enhancement**

This is a proposal to remove all access points to DOM Elements that are created via the `v()` and `w()` functions and managed through the Dojo 2 widget system.

When `nodes` are created through the Dojo 2 widget system leveraging the `v()` and `w()` functions, accessing DOM nodes can contravene the reactive architecture pattern and encourage widgets to become stateful, **or at worst indeterminate**

There are currently 2 first class supported mechanisms that enable consumers to gain DOM references on successful Element creation and Element updates - `onElementCreated` and `onElementUpdated`. 

**Note:** Both these hooks will be deprecated and eventually removed as part of these changes.

It is recognised that attributes from the DOM are required in order to create the UI layout desired, animations, focus (and more) and as part of this proposal, enhancements (linked to this epic) to `widget-core` will be completed to allow consumers to access this information in a readonly, reactive nature.

Finally, there will be occasions where needing a DOM Element is the only way to achieve certain functionality, i.e. working with external libraries that create their own DOM nodes - for these cases `widget-core` provides a higher order component called `DomWrapper` that wraps manually created DOM nodes and places them in the virtual DOM tree, while still allowing you to write to it in a reactive manner.

Supporting features for replacing direct DOM access are:
 * DOM Meta Mechanism
 * Focus management
 * Synthetic Events
 * DomWrapper

**Comment by sebilasse** [comment]
@agubler 
Question: What does

> all access points

mean ?

For the widgets I wrote the logic is similar to 
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/AutoControlledComponent.js
The `autoControlledProps` can't be set but any other can be set ...

This logic is not done yet for my dojo2/semantic ui integration but I want to start to write it now ;)
How would I deal with that after the change?

Just in case you are interested - I am attaching the code I did (Semantic views, elements and collections are nearly ready but modules [things with own JS logic] are not done yet)
[semantic0_0_4_Preview.zip](https://github.com/dojo/widget-core/files/1084038/semantic0_0_4_Preview.zip)

**Comment by agubler** [comment]
@sebilasse "All access points" refers to any existing way that a consumer can get a handle to a DOM element created via the widget-core.

This includes the `onElementCreated`/`onElementUpdated`, Maquette properties `afterCreate`/`afterUpdate` and the DOM elements within an event payload.

**Comment by agubler** [comment]
With the landing of #840 to remove outstanding escape hatch to the DOM and all other issue closed, we can consider this epic resolved.
