### ISSUE TITLE
Font imports in CSS not working, various CSS classnames not working

### ISSUE THREAD

**Issue by sebilasse** [dojo/widget-core#562]
```
./src/widgets/Icon/styles/icon.min.css
Module build failed: ModuleParseError: Module parse failed: /Users/sebi/Desktop/redaktorTS2/src/webcomponents/semantic/src/widgets/Icon/styles/fonts/icons.woff2 Unexpected character '�' (1:4)
You may need an appropriate loader to handle this file type.
```

The same happens for every font file (eot, otf) and many other files that can be imported in CSS.
Apart from that `reserved TypeScript word`s do not work but many well known CSS libraries have classes like e.g. `.delete.icon` ... 

Maybe this issue helps https://github.com/css-modules/css-modules/issues/95

**Comment by agubler** [comment]
@sebilasse this would be a `@dojo/cli-build` issue

**Comment by agubler** [comment]
Issue moved to [dojo/cli-build #154](https://github.com/dojo/cli-build/issues/154) via [**ZenHub**](https://www.zenhub.com/)
