### ISSUE TITLE
Support `undefined` as child

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#568]
**Enhancement**

Support `undefined` as a child type that will be filtered like `null`

**Comment by sebilasse** [comment]
@agubler Could the same be done for `this.classes` methods ?
<img width="875" alt="bildschirmfoto 2017-06-23 um 07 59 42" src="https://user-images.githubusercontent.com/750300/27468420-0e022c20-57ea-11e7-9c05-343f73094d7b.png">

**Comment by agubler** [comment]
@sebilasse I feel like it's a slightly different use case with classes as you are generally dealing with a known string from a css import and using a ternary to flip whether the class should be applied based on some state or property.

```ts
this.classes(this.properties.active ? css.active : null);
```

Having said that please feel free to open an issue for this request and it will get discussed and triaged appropriately.
