### ISSUE TITLE
Make properties mandatory for `w()`

### ISSUE THREAD

**Issue by sebilasse** [dojo/widget-core#572]
This would be the opposite of https://github.com/dojo/widget-core/issues/558 as commented there.

**Comment by agubler** [comment]
Properties are always mandatory for `w`, I assume you meant optional for `w`?

**Comment by sebilasse** [comment]
@agubler Off course, sorry [edited title].

**Comment by agubler** [comment]
@sebilasse Okay thanks! The `properties` cannot be made optional for `w` as it allows the type guarding for widgets with mandatory properties to be circumvented - In fact, as mentioned in the linked issue we have had to back out a similar change in the past #468.

(ps the title hadn't changed)
