### ISSUE TITLE
Consider applying core mixins to WidgetBase by default

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#581]
**Enhancement**

The main core mixins, `Themeable`, `I18n` and `Registry` provide functionality that could be automatically mixed in to `WidgetBase` by default. This would remove possible friction for consumer to need to deal with the mixin concept early on in Dojo 2 adoption.

The mixins are all additive functionality and shouldn't impact consumers who only need core `WidgetBase` functionality.

This would leave:

1) `Stateful`, which I think we should consider removing in favour of promoting use of typed class properties for any required internal state.
2) `Projector`, which would remain as an optional mixin to decorate a widget with functionality required to attach to the DOM.

**Comment by kitsonk** [comment]
I would be 👍 for `Themeable` and `Registry`.  I guess how heavy is `I18n` overall?  It feels sort of 50/50 it being fundamental.  Are all `@dojo/widgets` using it?

I think with `Stateful` we don't have a compelling use case at the moment, between `meta` and potentially injectors with whatever "app" becomes.  Agree with `Projector` comments.

**Comment by kitsonk** [comment]
@agubler is this still valid (undone)?  I don't think it is a discussion anymore because we all think it is a :+1:.  If still to do, will it make beta4, or should we move it to beta5?

**Comment by agubler** [comment]
@kitsonk perhaps with the changes coming to `Themeable` meaning it's only needed when theming is required, not to just use classes full stop, we could possibly leave it separate.

**Comment by kitsonk** [comment]
@agubler any further action on this? It feels that with other changes we have largely mitigated this issue?

**Comment by agubler** [comment]
Completely mitigated in my opinion, closing.
