### ISSUE TITLE
An empty string in fixed classes causes maquette error

### ISSUE THREAD

**Issue by sebilasse** [dojo/widget-core#592]
When you have an empty string in the arguments of `this.classes.fixed` (and maybe other this.classes methods) maquette has the error `The string did not match the expected pattern.`.
It might for example happen when arguments are destructured from a dynamically created Array.
Maybe the arguments could be filtered (?)

**Comment by kitsonk** [comment]
We should do something here.  No good passing something through that breaks other stuff.  The challenge though of course is that filtering everything for a few bad actors will be a performance hit on everyone, so maybe the right thing to do is raise a PR with maquette to handle it better.

**Comment by agubler** [comment]
At the moment we only support filtering `null`, perhaps we should filter all falsy values?
