### ISSUE TITLE
beforeRender does not work here

### ISSUE THREAD

**Issue by sebilasse** [dojo/widget-core#593]
Tried to use `beforeRender` as suggested in an issue before.
When I use it without decorator it is not called and with decorator it looks like

<img width="787" alt="bildschirmfoto 2017-06-24 um 14 15 18" src="https://user-images.githubusercontent.com/750300/27508547-db4a2f68-58e7-11e7-9fe7-e59909f20dcf.png">

**Comment by agubler** [comment]
It would be more helpful to have code snippets than screenshots, however this looks like you're just not calling the decorator.

```ts
@beforeRender()
protected myBeforeRender(renderFunc: () => DNode | DNode[], properties: any, children: any) {
// stuff
}
```
