### ISSUE TITLE
Consider performance/memory improvements with .classes() in Themeable

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#616]
**Enhancement** 

There are some improvements we can make in how we handle `this.classes()` in the Themeable mixin.  Specifically we are generating new functions every time.

**Comment by kitsonk** [comment]
@agubler will the be redundant with #732? (if so we can close this)

**Comment by agubler** [comment]
@kitsonk yup it should be, I'll resolve this as well when I raise the changes.
