### ISSUE TITLE
addDecorator called at the method level does not use decoratorMap

### ISSUE THREAD

**Issue by pottedmeat** [dojo/widget-core#622]
**Bug** 

Calling `addDecorator` from within an instantiated widget - specifically with a decorator such as `afterRender` which takes place after `render` - will add the callback to `_decoratorCache` without adding class-level decorators from `decoratorMap`.

**Comment by agubler** [comment]
I think initially there was a note in the readme that indicated that you cannot use decorators along with the functional alternative. However I just checked and that doesn't exist anymore....

I do agree that it should go down the same path for registering regardless of decorator or functional.

**Comment by pottedmeat** [comment]
It's interesting because the way the code is written, functional `addRender` would append to `beforeRender` but not `afterRender`.

**Comment by agubler** [comment]
Sorry I am not following, I think that the decorators are added all in the same way.... Using actual decorators they are added to a map keyed by the widget constructor and programatically they are directly added to the instances cache. On first use if there is nothing in the cache then it walks the inheritance tree to look up registered decorators the for the key requested and then stores that in the cache.

Obviously if a mixture is used then there will be something in the cache and the functions registered using the decorator annotation will be ignored.

**Comment by pottedmeat** [comment]
The cache isn't built until `getDecorator` is called. So `addDecorator` being called in `render` will happen after `getDecorator('beforeRender')` was called but before `getDecorator('afterRender')` is called. Meaning beforeRender will have `decoratorCache` populated but afterRender will not.

**Comment by agubler** [comment]
It's only built for the requested decorator key though right?

**Comment by pottedmeat** [comment]
Yeah. I'm just saying it has race conditions.

**Comment by agubler** [comment]
It's not race conditions per se, I believe that if you use programmatic API for decorators any annotated decorators would never be added to the cache for that specific decorator.

Ideally would like to see both the programmatic and annotated `addDecorator` logic be using the same code path.
