### ISSUE TITLE
Add support for "always widget render" hook

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#676]
**Enhancement**

There are scenarios when a hook to always consider a component `dirty` and therefore re-render regardless of the result of the property diff'ing similar to React's `shouldComponentUpdate`.

An existing use-case is the `Container` HOC which needs to always re-render regardless of the properties that it receives.

In `WidgetBase`:

```ts
protected alwaysRender() {
    return false;
}
```

overriding this in a component:

```ts
protected alwaysRender() {
    return true;
}
```

Should returning true skip the property diff'ing? Should the function receive any arguments (like the props)?

**Comment by agubler** [comment]
A suggestion is to expose the private `_dirty` property in `WidgetBase` via a protected function like `isDirty()`.

This would skip all diffs and reactions for the widget.

**Comment by matt-gadd** [comment]
I think `alwaysRender` as a protected function puts us in quagmire for the negative case - for example does returning `false` never render? or does it go back to doing a diffed based render?

There are 3 potential states for our rendering:
* always re-render
* diff based re-render
* never re-render

Given we have the middle one by default, we could perhaps just have decorators for the other 2? like `@alwaysRender()`, and `@neverRender()`. 

If `@alwaysRender()` skips the whole diff phase and basically just says all things have changed, we should probably also guard against people using the decorator if custom diffs/reactions have been registered in the mixin chain.

**Comment by agubler** [comment]
I see the possible confusion with an `alwaysRender` function returning `false. I think that's a nice suggestion, as using a decorator is more consistent with other mechanisms on `WidgetBase` (like `diffProperty`).
