### ISSUE TITLE
Support Functional Animations

### ISSUE THREAD

**Issue by rishson** [dojo/widget-core#70]
So currently, we support CSS animations, but we should also support functional animations with Maquette.

**Comment by rishson** [comment]
Refs #56

**Comment by agubler** [comment]
@matt-gadd @rishson @dylans I've added the discussion label to this because I think we need to think about whether we need/want to support programmatic animations at all.

A consumer can add a library such as velocity and use Maquette's in built support for functional animations if they need regardless.

**Comment by dylans** [comment]
So I guess the questions that I would ask:

* Do any widgets need non-CSS animations? (so far I assume not)
* If we don't want to include something, we should at least document/test the workflow for using something else so that it's not something like Fermat's last theorem to get it working.

**Comment by dylans** [comment]
We're running into this need with TitlePane (and Accordion), see https://github.com/dojo/widgets/pull/26#issuecomment-283113138 , so it's probably time to revisit adding this support.

**Comment by agubler** [comment]
Maquette supports this out the box but you need something like velocityjs to do so. The question is do we want to have a dependency on a third party library.

**Comment by matt-gadd** [comment]
Yes we have support right now like @agubler said. Just a case of picking something to use in `widgets`.

I think we should stay clear of `velocityjs` in favour of the native `animate` api if possible and polyfilling with https://github.com/web-animations/web-animations-js. But i'm sure their are other opinions.

**Comment by agubler** [comment]
I played with web-animations end of last year when originally looking at this, certainly seems appealing to me.

**Comment by dylans** [comment]
If it solves our needs, is decently engineered, and is licensed reasonably that seems ok to me. We can always replace it later if it doesn't work out for us. There are some interesting approaches out there to bind animation functions via CSS grammar which this does not seem to support, but I'm probably ok with not having that for now as well.

**Comment by dylans** [comment]
Or what @matt-gadd  said is fine as well!

**Comment by agubler** [comment]
@dylans / @matt-gadd I think we can create a real story here to consider bringing in the web-animations polyfill (by default) and having this as the supported mechanism for functional animations. Maquette will support them out the box via the existing `exitAnimation`, `enterAnimation` and `updateAnimation` properties.

**Comment by dylans** [comment]
> @dylans / @matt-gadd I think we can create a real story here to consider bringing in the web-animations polyfill (by default) and having this as the supported mechanism for functional animations. Maquette will support them out the box via the existing exitAnimation, enterAnimation and updateAnimation properties.

I'm fine with that, let's create as a beta2 issue.

**Comment by tomdye** [comment]
Closing as superseded by https://github.com/dojo/widget-core/issues/657
