### ISSUE TITLE
Remove warn for overriding css classes

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#716]
**Enhancement**

A pattern for extending/overriding css styles by extending a widget and providing a new css object to the sub classes widget via `@theme` has been agreed.

```ts
// BaseWidget.ts
interface baseCss {
    widget: string
};

@theme(baseCss)
class BaseWidget extends WidgetCore {}
```

To override the class `widget` provided by `BaseWidget`, `ExtendedBaseWidget` provides its own css with the same class key which the `ExtendedBaseWidget` will use.

```ts
// ExtendedBaseWidget.ts
interface extendedBaseCss {
    widget: string
};

@theme(extendedBaseCss)
class ExtendedBaseWidget extends BaseWidget {}
```

This means that the original warning `Duplicate base theme class key '${key}' detected, this could cause unexpected results` is no longer relevant, as it is _expected_ that multiple css objects with the same keys can be used and the styles from the sub class widget will override its parents.

**Comment by maier49** [comment]
Looks like this was already addressed by #734
