### ISSUE TITLE
Tutorial feedback 003

### ISSUE THREAD

**Issue by umaar** [dojo/widget-core#726]
After reading a tutorial I have this feedback:

Step 7: "You may notice that we are calling this.classes with the container class as an argument. classes is a method provided by the ThemeableMixin which adds the specified class or classes to the widget, and verifies that they exist as part of the widget’s theme." To avoid having to write:

const WorkerContainerBase = ThemeableMixin(WidgetBase);
"

...for any widget which needs CSS functionality, would it make sense for the WidgetBase to include such CSS functionality by default?

Link: https://dojo.io/tutorials/003_creating_widgets/#7

**Comment by kitsonk** [comment]
Covered by dojo-core#581.  If this happens, we would need to update the tutorials to reflect that.
