### ISSUE TITLE
Create meta for containing focus

### ISSUE THREAD

**Issue by smhigley** [dojo/widget-core#729]
**Enhancement**

From the widgets focus management issue (https://github.com/dojo/widgets/issues/309#issuecomment-339100993):

> **Provide meta information about whether focus is within a given node**
>
>This can be handled like a combination of Drag and Intersection meta. Similar to Drag, it will need a document-level event listener for the focus event, and like Intersection it can invalidate when focus moves into or out of a provided node.

I imagine the API would be something like:
`public get(key: string): boolean`

**Comment by smhigley** [comment]
Based on discussions with @matt-gadd, I think it would be a good idea to include setting `element.focus()` in this Meta. Although it blurs the line of what constitutes "meta," the Meta tool provides a clean, typed interface to touch any given DOM node in exactly this sort of way. Animation Meta also provides precedent for blurring the line between getting and setting "meta."

This would solve the first point from my comment on the [original focus issue](https://github.com/dojo/widgets/issues/309#issuecomment-339100993).

From Matt G:
> I agree the term `meta` is becoming less and less focused on i think what i originally intended anyway (in my head anyway). one thing it does currently do better than all the other mechanisms (mixins, decorators and decorating nodes generally), is it gives you the dom node easily, it gives you access to the scope of the widget instance, and it makes typing straightforward, and you don’t have to deal with decorating nodes, so it’s almost like the mechanism has more worth than the actual name `meta` at this point

**Comment by smhigley** [comment]
Revisiting where we handle setting focus:

I understand the desire to keep Meta pure, and not use it to perform DOM changes. On the other hand widget properties also don't fit focus management well, since (in my head) the DOM should reflect and be controlled by widget properties for any given render. Focus is different from current widget properties in that it will sometimes need to be set, but should never be actively controlled. If we were to try to handle it with something like `focus: boolean` we would need:

A) a built-in way to prevent calling focus multiple times in multiple renders if the widget user forgets to set `focus: false`
B) An easy way to call focus multiple times on the same node

Point A means that we'll need some sort of internal state or diffing across renders to determine if `focus: true` should really call focus. The end result is a property of `focus: true` does not actually indicate that the VNode in question has focus. Point B means that a widget user will need to create some sort of internal state to handle focus for every node they may want to call focus on, and deal with both `focus` and `onFocusCalled`. This is essentially what we do now and I feel it's too heavy for something that should be simple, and it still doesn't feel conceptually pure.

Expanding Meta to allow `set` works very well for VNodes, but it still fails when it is necessary to call focus on a child widget. I think it might be helpful to either expand Meta or create something similar that will provide information about widgets by key, where the child widget would need to be designed to expose certain information (e.g. "inputNode" or "focusNode"). This comes from React's `refs`, although in my opinion `refs` exposes too much of the underlying DOM node or component instance.

Looking at React, it seems they've run into a similar problem. They specifically call out focus management as one of the few reasons one might need to use the `ref` pattern, along with text selection, media playback, and imperative animations. I also looked at Vue's recommended focus pattern which seems to be `vue-focus`. It's more reactive, but it suffers all the issues we're currently coming up against. It will steal focus if the component's internal `this.focus` state isn't correctly handled, and involves a lot of work for something that should be easy.

**Comment by smhigley** [comment]
The things remaining to do on this issue after the Focus Meta PR are as follows:

- Find a better, more reactive way to set focus on VNodes
- Find any way at all to set focus on child widgets
- Should probably make it possible to set focus on the first focusable node within a given VNode
- Make it possible to focus a node on insertion (use cases: dialog, tab content, navigating between pages in a SPA)

**Comment by agubler** [comment]
@smhigley do you think we can close this issue and raise specific issues to address additional functionality?

**Comment by smhigley** [comment]
Closing in favor of #845
