### ISSUE TITLE
Remove `set()` and `_payload` from Injector

### ISSUE THREAD

**Issue by devpaul** [dojo/widget-core#753]
**Enhancement**

[`Injector`](https://github.com/dojo/widget-core/blob/master/src/Injector.ts) is commonly used a base class that provides itself and its own data via Injector's `get()` method. This is so common that [the tutorial even uses the Injector in this way](https://dojo.io/tutorials/1010_containers_and_injecting_state/#1). It extends `Injector` then passes an empty object literal to `super({})` and overrides `get()`.

The problem is, `set()` and `_payload` mean nothing in when an Injector is extended.

**Code**

```typescript
class MyInjector extends Injector {
    updated: number;
    constructor() {
        super({});
        this.updated = Date.now();
    }
    get(): MyInjector {
        return this;
    }
}
```

```typescript
const injector: MyInjector;

// Somebody from Dojo 1 might expect this to update properties on the injector
injector.set({ updated: Date.now() })
```

I recommend removing `set()` and `_payload` from `Injector` or make an Injector abstract/interface/or base class that only has `get()` and extends `Evented` for invalidate.

**Comment by mwistrand** [comment]
When working with [`@dojo/stores`](https://github.com/dojo/stores) or [`Redux`](https://github.com/reactjs/redux), the store will be passed directly to the injector's constructor, which is how `Injector` is _supposed_ to be used. For example, see the [Redux injector in `@dojo/interop`](https://github.com/dojo/interop/blob/master/src/redux/ReduxInjector.ts) and the [proposed `@dojo/stores` injector](https://github.com/dojo/stores/issues/141).

Passing an empty object to `super` and returning `this` from `get()` represents the case where an application is not yet complex enough to justify a full-featured store; but it combines both the store and injector functionalities, and as such is arguably a violation of separation of concerns. In other words, in my opinion the current `Injector` matches what I'd expect of it. So while the aforementioned pattern may be common for simpler applications, that won't be the case for more complex applications that need a complete store.

**Comment by mwistrand** [comment]
One additional option that could help clean this up is to 1) make the constructor's payload optional and 2) set the initial payload to `this` when nothing is passed to the constructor. As such, the example case would be reduced to:

```typescript
class MyInjector extends Injector {
    updated: number;
    constructor() {
        super();
        this.updated = Date.now();
    }
}
```

**Comment by agubler** [comment]
As per the discussion in https://github.com/dojo/widget-core/pull/790#issuecomment-348218617 regarding the pattern, I think we can close this and update the tutorials to demonstrate the correct pattern.
