### ISSUE TITLE
CSS Animations and vdom, support of IE9

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#757]
**Discussion**

It was discussed that we might want to reconsider support for IE9 on some/any packages (Refs: dojo/meta#40).  If that is the case, the move to internalising the vdom has removed the "shim" that was provided by Maquette to support CSS Animations in IE9.

If we wanted to consider supporting it, we would need to re-provide that functionality in some fashion.

**Comment by matt-gadd** [comment]
Lets close this as any kind of continued legacy support issue now would be under dojo/meta.
