### ISSUE TITLE
WebAnimations should be moved to shim

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#770]
**Enhancement**

The shim/polyfill for WebAnimations should be migrated to `@dojo/core/shim` in the same fashion as PEP is provided.

**Comment by kitsonk** [comment]
Also PEP needs to be moved.

**Comment by agubler** [comment]
@tomdye is this done now?

**Comment by tomdye** [comment]
This has been completed via: https://github.com/dojo/shim/pull/128

**Comment by tomdye** [comment]
There is still work to be done here to move the dependency and import into `@dojo/shim`
