### ISSUE TITLE
AnimationProperties interface needs changing to string enum

### ISSUE THREAD

**Issue by tomdye** [dojo/widget-core#802]
**Bug** 

current typing for AnimationProperties has `fill` and other fields defined as:

`fill?: 'none' | 'forwards' | 'backwards' | 'both' | 'auto';` 

But when trying to use it with `fill: 'forward'` it is throwing a type error.
There should all be changed to use string enums instead.

**Comment by kitsonk** [comment]
As discussed offline, this isn't really a bug, it has to do with how the properties are create and their type inferred.

So if anything it would be an enhancement.

**Comment by agubler** [comment]
I guess although this isn’t a big in Typescript, could be argued it is a bug in the usage intended for the animations meta

**Comment by tomdye** [comment]
Agreed, I think this needs working on

**Comment by tomdye** [comment]
Looks like `@types/web-animations-js` uses `type AnimationEffectTimingFillMode = "none" | "forwards" | "backwards" | "both" | "auto";` but it is not exported.
When converting our `AnimationTimingProperties` object to use a string enum the following error is thrown:

```
