### ISSUE TITLE
Custom elements do not have access to the properties of their children

### ISSUE THREAD

**Issue by pottedmeat** [dojo/widget-core#809]
**Bug** 

In order to leverage custom elements, we wrap our rendering system in a special `WNode` that links the custom element with the widget instance.

Unfortunately, this means that widgets that look through their children and read property values (and in tab containers look to see if their children have children) are going to instead see the properties and children that are part of this special `WNode` wrapper.

I have a [branch](https://github.com/pottedmeat/widget-core/tree/bug-attach-custom-elements) that adds getters to our `WNode` for `properties` and `children` that pass through the values of the widget instance. Another [branch](https://github.com/pottedmeat/widgets/tree/bug-attach-custom-elements) exists for widgets with a demo page to load the tab container as a custom element.

Even though my code looks like it's making changes to the previous functionality, I've written the code to make every attempt to leave it exactly as it was. All I've done is to add the getters I mentioned above to the `WNode` object, which was previously a Plan Old JavaScript Object.

**Comment by matt-gadd** [comment]
@pottedmeat thanks for the write up. I did try your branch, but creating a `WNode` with getters isn't going to work as the parent can then no longer then make changes to the `properties` or `children` itself. For example this completely breaks the custom element menu example which passes an `onSelected` function to the children.

**Comment by matt-gadd** [comment]
The detailed write up and examples were extremely useful for some of the rewrite I have been working on here: https://github.com/dojo/widget-core/pull/864 👍 , unfortunately Custom Element support for children with the same authoring patterns is quite a tough/awful slog!

**Comment by matt-gadd** [comment]
fixed as part of https://github.com/dojo/widget-core/pull/864, hopefully
