### ISSUE TITLE
Update setting focus on VNodes, widget children

### ISSUE THREAD

**Issue by smhigley** [dojo/widget-core#845]
**Enhancement** 

Continuation of #729. Now that Focus Meta exists, we need a better way to reactively set focus on VNodes and any way at all to set focus on widget children.

Things to solve: 
- Find a better, more reactive way to set focus on VNodes
- Find any way at all to set focus on child widgets
- Should probably make it possible to set focus on the first focusable node within a given VNode
- Make it possible to focus a node on insertion (use cases: dialog, tab content, navigating between pages in a SPA)

**Comment by schontz** [comment]
I'm not familiar enough with widget-core to be making informed suggestions, but is seems that there are multiple situations where a kind of `beforeNextRender` would be effective. Would it be possible to have some kind of `beforeNextRender` queue that could contain functions to run once? Then you won't run into issues of an element always stealing focus or similar things.

It might look like this:
```typescript
this.onBeforeNextRender(() => {
    this.meta(Focus).set('my-widget');
});
```

**Comment by matt-gadd** [comment]
@schontz 

a) you can already run things after a render via deferred properties (which is effectively the same as `beforeNextRender` in your case): https://github.com/dojo/widget-core/pull/736

b) the `focus` property is special in that it will only focus once if a boolean is passed (it is only constantly set if a function is passed): https://github.com/dojo/widget-core/pull/848

**Comment by schontz** [comment]
@matt-gadd #736 does part of what I'm asking, but I think it is a little different. I was thinking of a queue that gets cleared at the next `render` so they only **run once.**

**Comment by agubler** [comment]
@schontz setting `focus` to `true` on a `VNode` does only set focus once. Subsequent renders with the `focus` property set to `true` will not call `focus` again.

**Comment by schontz** [comment]
OK. I'll take a look. Thank you.

**Comment by agubler** [comment]
Things to solve:

* Find a better, more reactive way to set focus on VNodes
  * This has been solved by supporting the `focus` property on VNodes
* Find any way at all to set focus on child widgets
  * I think this has mostly been solved by the `FocusMixin`
* Should probably make it possible to set focus on the first focusable node within a given VNode
  * This breaks encapsulation so something that we are unlikely going to be able to support - Using the focus mixin it is up to the author to determine what getting passed `focus = true` means and perform focus on a node.
* Make it possible to focus a node on insertion (use cases: dialog, tab content, navigating between pages in a SPA)
  * This is also supported by the `focus` property on a `VNode`

I think these are mostly completed in at least a basic way, so closing this issue. Any future focus issues are likely to be focused enhancements (get it!?).
