### ISSUE TITLE
Widget Specifications

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#85]
We need to specify a list of tentative foundational widgets, so we can whittle them down and figure out the priority order to build them.  We should create a table in the following format:

|Class Name|Description|Type|Sub Widget Classes|
|---|---|---|---|
|*ClassName*|*A simple description of the widget*|*Simple/Composite/Container*|*Sub or Child Widget Classes*|

**Comment by bitpshr** [comment]
Preliminary list, pending discussion with @Tomdye. I didn't include charts.

## Form Widgets

### Primary

Form
Button
Checkbox
ComboBox (optionally flag unmatched text)
Date
Email
Number
Password
Radio
Select (optional multiple selection)
Textarea

### Secondary

Color
Datetime
File
Month
Range
Reset
Search
Submit
Tel
Text
Time
Url
Week

## Layout Widgets

AccordionPanel
TabbedPanel

## Misc. Widgets

ConfirmDialog
Dialog
Menu
Tooltip

**Comment by smhigley** [comment]
I like it! I would just propose a couple very minor changes:

- Button and Slider could use the corresponding native `<button>` and `<input type="range">` elements
- FileInput probably won't be able to use a styled HTML element alone if we want drag and drop functionality
- I think Select should be split into a native single-select dropdown and a separate multi-select component. WebAIM recommends against using the native multi-select box for accessibility, so we could use checkboxes under the hood to achieve the same functionality.

**Comment by dylans** [comment]
Other suggestions (summarized from another thread):

* User resizable panel/region (e.g. like that found in https://user.sitepen.com/~kkelly/app-example/_build/src/ )
* Dialog should also be modeless in addition to modal (e.g. FloatingPane from Dojo 1)
* Should probably decouple DatePicker/icon/dropdown so users can show in various states)
* Slider horizontal and vertical?
* Switch (e.g. on/off found on mobile)
* Constraints on DatePicker
* TimePicker ?
* Menu on desktop vs. mobile will probably behave quite differently... may also want the hamburger style menu on desktop)

@smhigley The HTML5 slider doesn't give much in the way of CSS styling, or does it?

Also agree that FileInput via HTML DnD is important.

**Comment by smhigley** [comment]
@dylans See http://codepen.io/smhigley/pen/ObWbdy for CSS styling examples with the native range input. It's also possible to switch horizontal/vertical with CSS.

**Comment by dylans** [comment]
> @dylans See http://codepen.io/smhigley/pen/ObWbdy for CSS styling examples with the native range input. It's also possible to switch horizontal/vertical with CSS.

👍 nice!

**Comment by dylans** [comment]
Issue moved to [dojo/widgets #24](https://github.com/dojo/widgets/issues/24) via [**ZenHub**](https://www.zenhub.com/)
