### ISSUE TITLE
Create base registry by default and only define injectors against the base registry

### ISSUE THREAD

**Issue by agubler** [dojo/widget-core#895]
**Enhancement**

It would be useful to be able to set an injector on the base registry within a widget. To support the functionality we'd create a base registry by default for the projector and set it on the core properties such that it will be passed down to the widget tree. The default registry will be able to be overridden by passing a registry as a property on the projector as normal.

The `RegistryHandler` will only allow setting and getting injectors on the base registry as setting an injector on a locally scoped registry isn't useful.

**Comment by dylans** [comment]
Closing this issue for now. We will open another issue to address this differently in the future.
