### ISSUE TITLE
Failures on functional tests with Android 4.4

### ISSUE THREAD

**Issue by kitsonk** [dojo/widget-core#92]
Intermittent failures on Android 4.4

**Comment by agubler** [comment]
I don't think the same functionals exist any more, perhaps we should try android 4.4 again

**Comment by dylans** [comment]
From what I can tell, Sauce Labs and Appium have not released their fixes yet for the Android Emulator 2 type, which will also let us target newer versions of Chrome Driver. So I believe the issues were were seeing were more WebDriver related than bugs we were having, but I guess it's worth trying again.

**Comment by agubler** [comment]
Closing this as we do not have the functional tests that were failing anymore and also there are other issues with Android (not just 4.4) that means the platform has been removed from the intern test config.
