### ISSUE TITLE
[QUESTION] Add data-attribute to simple div

### ISSUE THREAD

**Issue by vogloblinsky** [dojo/widget-core#925]
How can i simply create this with dojo2 ?

```html
<button data-value="10">Load 10</button>
```

I am creating my button like that.

```
v('button', {
	onclick: this.handleLoad
}, ['Load 10'])
```

Thanks

**Comment by agubler** [comment]
Adding an attribute like `data-value` would look something like this:

```ts
v('button', { 'data-value': '10' }, [ 'Load 10' ]);
```

and can be seen in this [codesandbox.io](https://codesandbox.io/s/9ql0q2q16o)

**Comment by vogloblinsky** [comment]
Thanks works fine.

May be a dedicated section in the documentation could be fine.
