### ISSUE TITLE
Views for multiple routes seen at once

### ISSUE THREAD

**Issue by nicknisi** [dojo/widget-core#931]
**Bug** 

Package Version: 2.0.0

**Code**

An example of this can be seen at https://github.com/aldyn/dojo-tree.

**Expected behavior:**

Only the view associated with the current route should be displayed.

**Actual behavior:**

When navigating from a path (e.g. "test/1/test2/test3") to a different path, the views assigned to each path are both shown.

**Comment by agubler** [comment]
Issue moved to [dojo/routing #139](https://github.com/dojo/routing/issues/139) via [**ZenHub**](https://www.zenhub.com/)

**Comment by szwoelf** [comment]
Hi again!

Here also we have the problem, that with your fix our inital fix does not work anymore. The order of nodes is not preserved during clicking through the application and navigating around.

Possibly that is also the same like in https://github.com/dojo/widget-core/issues/930.

Thanks in advance and sorry for your inconvenience,
 Simon + Aldin
