### ISSUE TITLE
extraClasses crashes your app if class names contain leading or trailing whitespace

### ISSUE THREAD

**Issue by schontz** [dojo/widget-core#947]
**Bug** 

When you pass a string value with leading or trailing whitespace to `extraClasses` it causes your app to crash/never start, even though it compiles just fine.

```typescript
w(Button, {
   extraClasses: 'dontCrash ', // notice trailing whitespace
}, ['Button will build but page will crash']);
```

Package Version: 2.0

**Expected behavior:**

App should run and apply `dontCrash` class to the `Button`.

**Actual behavior:**

App never shows up. Instead the whole thing crashes: 
```
vdom.ts:198 Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
vdom.ts:1056 Uncaught TypeError: Cannot read property 'parentVNode' of undefined
```

**Comment by sebilasse** [comment]
@schontz 
Can we give extraClasses a plain `string`?
Shouldn't it be an object like `{root: 'dontCrash '}`?

```TypeScript
export interface ThemedProperties<T = ClassNames> extends WidgetProperties {
	injectedTheme?: any;
	theme?: Theme;
	extraClasses?: { [P in keyof T]?: string };
}
```

**Comment by tomdye** [comment]
Spaces are used within css modules to denote when multiple classes are to be applied to a single node. This pattern is used whenever you use `composes` within your css file. As such, a classname with a trailing space is invalid. You can't apply a classname with a space via css either. So I'd recommend that you `trim` your strings before passing them to `extraClasses`.

I hope this resolves your issue.

**Comment by schontz** [comment]
Sorry for the error in my example, but the issue remains. I didn't run into the issue with that kind of trivial example, e.g. adding a space after the class name, but of one where the classes are put together programmatically. Note that the issue also arises if you put 2 spaces between class names, e.g. `root: 'one  two'` will compile just fine but crash your whole app. `trim` will do you no help in this situation.

Since this issue allows your app to transpile just fine but not run *at all* it seems like there should at least be some fix/warning about it.
